import type { Metadata } from "next";
import Link from "next/link";
import { HotelGptFlowLibrary } from "@/components/admin/hotelgpt-flow-library";

export const metadata:Metadata={title:"Flow Library · Super Admin · AiFrogi",robots:{index:false,follow:false}};

export default function AdminFlowLibraryPage(){return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8"><header className="flex flex-col gap-5 border-b border-black/8 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="product-eyebrow">Super Admin · versioned category intelligence</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Flow Library</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#68645c]">Master templates define safe starting journeys. Every hotel receives an independent draft copy; no live hotel flow is silently replaced.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/sovereign-intelligence" className="rounded-full border border-black/10 bg-white px-5 py-2.5 text-sm font-bold">Core Intelligence</Link><Link href="/admin/customers" className="rounded-full bg-[#101010] px-5 py-2.5 text-sm font-bold text-white">Hotel workspaces</Link></div></header><section className="grid gap-4 bg-[#101010] p-5 text-white md:grid-cols-3"><Layer number="01" title="Core Intelligence" copy="Safety, intent, context, privacy and evidence."/><Layer number="02" title="Bot Intelligence" copy="Hotel-approved facts, policy, tone and authority."/><Layer number="03" title="Flow Intelligence" copy="Journey, smart output and operational outcome."/></section><HotelGptFlowLibrary/><p className="rounded-2xl border border-[#d8c278] bg-[#fff9e8] p-5 text-sm leading-6 text-[#5e4a17]"><strong>Publication rule:</strong> Pre-Stay templates may create public menu entries. In-Stay templates remain inside verified-stay access and can never enter the public menu.</p></main>}

function Layer({number,title,copy}:{number:string;title:string;copy:string}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-xs font-bold text-[#e2c66d]">{number}</span><h2 className="mt-3 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/60">{copy}</p></div>}
