"use client";

import { useState } from "react";
import type { TenantFlowDefinition, TenantFlowTemplateKey } from "@/lib/tenant-flow-intelligence";
import { TENANT_FLOW_TEMPLATES } from "@/lib/tenant-flow-intelligence";

export function FlowIntelligenceWorkspace({ initialFlows, canManage }: { initialFlows: TenantFlowDefinition[]; canManage: boolean }) {
  const [flows, setFlows] = useState(initialFlows);
  const [selectedId, setSelectedId] = useState(initialFlows[0]?.id || "");
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const selected = flows.find(item => item.id === selectedId);
  async function act(body: object) {
    setBusy(true); setNotice("");
    try { const response = await fetch("/api/flow-intelligence", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setFlows(payload.flows); if (payload.flow) setSelectedId(payload.flow.id); setNotice(body && "action" in body && body.action === "publish" ? "Published. This flow is now connected to the bot Main Menu." : "Flow saved."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Could not update the flow."); }
    finally { setBusy(false); }
  }
  function patch(field: keyof TenantFlowDefinition, value: string) { if (!selected) return; setFlows(items => items.map(item => item.id === selected.id ? { ...item, [field]: value } : item)); }
  return <div className="space-y-6">
    <header className="rounded-2xl border border-[var(--border)] bg-white p-6"><p className="product-eyebrow">Tenant Intelligence · Flow Intelligence</p><h1 className="mt-2 text-3xl font-semibold">Design how this bot helps a visitor</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--text-muted)]">Each bot owns its flows. AiFrogi answers from approved tenant knowledge first; if a reliable answer is unavailable, it offers human help or a consented callback.</p></header>
    <section className="rounded-2xl border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Start from a governed template</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{TENANT_FLOW_TEMPLATES.map(template => <article key={template.key} className="rounded-xl border border-[var(--border)] p-4"><h3 className="font-semibold">{template.name}</h3><p className="mt-1 text-sm leading-5 text-[var(--text-muted)]">{template.description}</p><button disabled={!canManage || busy} onClick={() => act({ action: "create", templateKey: template.key as TenantFlowTemplateKey })} className="mt-3 text-sm font-semibold text-[var(--primary-strong)]">Use template →</button></article>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="rounded-2xl border border-[var(--border)] bg-white p-4"><h2 className="font-semibold">This bot’s flows</h2><div className="mt-3 grid gap-2">{flows.map(flow => <button key={flow.id} onClick={() => setSelectedId(flow.id)} className={`rounded-xl border p-3 text-left ${selectedId === flow.id ? "border-[#8a6a16] bg-[#faf6e9]" : "border-[var(--border)]"}`}><strong className="block text-sm">{flow.name}</strong><span className="mt-1 block text-xs text-[var(--text-muted)]">{flow.status.toLowerCase()} · v{flow.version}</span></button>)}{!flows.length ? <p className="text-sm text-[var(--text-muted)]">Choose a template to create the first flow.</p> : null}</div></aside>
      <main className="rounded-2xl border border-[var(--border)] bg-white p-5">{selected ? <><div className="grid gap-4 md:grid-cols-2"><label><span className="field-label">Flow name</span><input className="product-input mt-2" value={selected.name} disabled={!canManage} onChange={e => patch("name", e.target.value)} /></label><label><span className="field-label">Main Menu label</span><input className="product-input mt-2" value={selected.menuLabel} maxLength={54} disabled={!canManage} onChange={e => patch("menuLabel", e.target.value)} /></label></div><label className="mt-4 block"><span className="field-label">Opening customer request</span><textarea className="product-input mt-2 min-h-24" value={selected.openingQuestion} maxLength={400} disabled={!canManage} onChange={e => patch("openingQuestion", e.target.value)} /><small className="mt-1 block text-[var(--text-muted)]">The visitor sees this before sending it. The answer still comes from this bot’s approved knowledge.</small></label><h2 className="mt-6 font-semibold">Controlled flow</h2><div className="mt-3 flex flex-col gap-2 xl:flex-row xl:items-stretch">{selected.steps.map((step, index) => <div key={step.id} className="flex flex-1 items-center gap-2"><article className="h-full flex-1 rounded-xl border border-[var(--border)] bg-[#fbfaf7] p-3"><span className="text-[10px] font-bold text-[#8a6a16]">{step.type.replaceAll("_", " ")}</span><p className="mt-1 text-sm font-semibold">{step.label}</p></article>{index < selected.steps.length - 1 ? <span aria-hidden="true" className="hidden text-[#8a6a16] xl:block">→</span> : null}</div>)}</div><div className="mt-6 flex flex-wrap gap-3 border-t border-[var(--border)] pt-5"><button disabled={!canManage || busy} onClick={() => act({ action: "save", flow: selected })} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold">Save draft</button><button disabled={!canManage || busy} onClick={() => act({ action: "publish", id: selected.id })} className="rounded-full bg-[#126b50] px-5 py-2.5 text-sm font-semibold text-white">Approve &amp; publish</button>{selected.status === "PUBLISHED" ? <button disabled={!canManage || busy} onClick={() => act({ action: "pause", id: selected.id })} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold">Pause</button> : null}<button disabled={!canManage || busy} onClick={() => act({ action: "delete", id: selected.id })} className="px-3 py-2 text-sm text-red-700">Delete</button></div></> : <p className="text-sm text-[var(--text-muted)]">No flow selected.</p>}{notice ? <p role="status" className="mt-4 rounded-lg bg-[var(--info-soft)] px-4 py-3 text-sm">{notice}</p> : null}</main></div>
  </div>;
}
