import Link from "next/link";
import { Icon } from "@/components/icons";
import { listOrganizationsForAdmin } from "@/lib/repositories/onboarding-repository";
import { listSupportTickets } from "@/lib/repositories/support-repository";
import { getDb } from "@/lib/db";
import { getMessageMatrix } from "@/lib/message-matrix";
import { getOperationalHealthSnapshot } from "@/lib/operational-health";
import { getCapacitySnapshot } from "@/lib/capacity-advisor";
import { getAdminSupportActions } from "@/lib/support-notifications";
import { getAdminLeadAwareness } from "@/lib/lead-insights";

export const dynamic = "force-dynamic";
const DAY = 86_400_000;
const format = (value: Date) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(value);

export default async function AdminPage() {
  const db = getDb();
  const [organizations, tickets, failedMessages, messageMatrix, operationalHealth, capacity, leadAwareness] = await Promise.all([listOrganizationsForAdmin(), listSupportTickets({ includeMessages: true }), db?.leadMessage.count({ where: { deliveryStatus: { startsWith: "failed" } } }) ?? 0, getMessageMatrix(), getOperationalHealthSnapshot(), getCapacitySnapshot(), getAdminLeadAwareness()]);
  const now = new Date();
  const newCustomers = organizations.filter((item) => now.getTime() - item.createdAt.getTime() <= 7 * DAY);
  const supportActions = getAdminSupportActions(tickets);
  const renewals = organizations.map((organization) => ({ organization, due: organization.subscription?.plan.code === "TRIAL" ? organization.subscription.trialEndsAt : organization.subscription?.currentPeriodEnd })).filter((item): item is { organization: typeof organizations[number]; due: Date } => Boolean(item.due) && item.due!.getTime() >= now.getTime()).sort((a,b) => a.due.getTime() - b.due.getTime()).slice(0, 6);
  const live = organizations.filter((item) => item.botProfile?.status === "LIVE").length;
  const paused = organizations.filter((item) => item.status === "SUSPENDED" || ["PAUSED","SUSPENDED","CANCELLED"].includes(item.subscription?.status || "")).length;
  const alerts = supportActions.length + failedMessages + paused;
  const creditSnapshot = {
    used: messageMatrix.reduce((sum, item) => sum + item.usage.aiReplies, 0),
    purchasedRemaining: messageMatrix.reduce((sum, item) => sum + item.aiCredits.purchasedRemaining, 0),
    promotionalRemaining: messageMatrix.reduce((sum, item) => sum + item.aiCredits.promotionalRemaining, 0),
    grantReviews: messageMatrix.filter((item) => item.freeCreditRecommendation.suggested).length
  };
  const leadSnapshot = leadAwareness.reduce((summary, item) => ({ total: summary.total + item.total, gradeA: summary.gradeA + item.gradeA, unattended: summary.unattended + item.unattended }), { total: 0, gradeA: 0, unattended: 0 });

  return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-black/8 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.18em] text-[#8a6a16]"><span className={`h-2 w-2 rounded-full ${alerts ? "bg-[#cf4d43]" : "bg-[#36a77a]"}`} />{alerts ? `${alerts} operational signals` : "Operations clear"}</div><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Command Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#68645c]">The working dashboard for customer launch, revenue continuity and support—not a presentation screen.</p></div><Link href="/admin/onboard" className="flex min-h-12 items-center gap-3 rounded-full bg-[#b28728] px-6 text-sm font-bold text-white"><Icon name="sparkles" />Start onboarding</Link></header>

    <section className="grid overflow-hidden border border-white/70 bg-white sm:grid-cols-2 xl:grid-cols-4">{[["Customers",organizations.length,"All workspaces"],["New · 7 days",newCustomers.length,"Recent intake"],["AI Bots live",live,"Serving users"],["Attention",alerts,"Support + billing"]].map(([label,value,copy],index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className={`mt-3 block text-3xl ${label === "Attention" && Number(value) ? "text-[#b53b33]" : ""}`}>{value}</strong><small className="mt-2 block text-[#817b72]">{copy}</small></div>)}</section>

    <section className="overflow-hidden border border-white/70 bg-[#f4f0e7]"><PanelHead eyebrow="AI credit position · today" title="Usage and credits remaining" href="/admin/billing" /><div className="grid bg-white sm:grid-cols-2 xl:grid-cols-4">{[["AI replies used", creditSnapshot.used, "Current billing periods"], ["Purchased left", creditSnapshot.purchasedRemaining, "Paid prepaid credits"], ["Promotional left", creditSnapshot.promotionalRemaining, "Super Admin grants"], ["Grant reviews", creditSnapshot.grantReviews, "Suggestions awaiting review"]].map(([label, value, copy], index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className="mt-3 block text-3xl">{Number(value).toLocaleString("en-IN")}</strong><small className="mt-2 block text-[#817b72]">{copy}</small></div>)}</div></section>

    <section className="overflow-hidden border border-white/70 bg-white"><PanelHead eyebrow="Operational reliability" title="Retries, incidents and notification health" href="/admin/audit" /><div className="grid sm:grid-cols-2 xl:grid-cols-4">{[["Automation retries", operationalHealth.automationRetries], ["Dead jobs", operationalHealth.deadJobs], ["Open incidents", operationalHealth.openIncidents], ["Billing email failures · 24h", operationalHealth.billingEmailFailures24h]].map(([label, value], index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className={`mt-3 block text-3xl ${Number(value) ? "text-[#b53b33]" : "text-[#17694f]"}`}>{Number(value).toLocaleString("en-IN")}</strong><small className="mt-2 block text-[#817b72]">{Number(value) ? "Review required" : "Clear"}</small></div>)}</div></section>

    <section className="overflow-hidden border border-white/70 bg-white"><PanelHead eyebrow={`Capacity advisor · ${capacity.advisor.tone}`} title="100 bots · 10,000 daily AI replies" href="/admin/capacity" /><div className="grid sm:grid-cols-2 xl:grid-cols-4">{[["Configured bots", capacity.configuredBots, `Target ${capacity.target.bots}`], ["AI replies today", capacity.repliesToday, `Target ${capacity.target.dailyReplies.toLocaleString("en-IN")}`], ["Projected daily", capacity.projectedDailyReplies, "Seven-day average"], ["VPS memory", capacity.host.memoryPercent, capacity.host.memoryPercent === null ? "Not measured" : `${capacity.host.cpuCores} CPU cores`]].map(([label, metric, copy], index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className="mt-3 block text-3xl">{metric === null ? "—" : Number(metric).toLocaleString("en-IN")}{label === "VPS memory" && metric !== null ? "%" : ""}</strong><small className="mt-2 block text-[#817b72]">{copy}</small></div>)}</div><div className="border-t border-black/6 bg-[#f7f6f2] px-6 py-4 text-sm text-[#68645c]">{capacity.advisor.actions[0]}</div></section>

    <section className="overflow-hidden border border-white/70 bg-white"><PanelHead eyebrow="Lead awareness · privacy-safe" title="Captured lead volume by workspace" href="/admin/customers" /><div className="grid border-b border-black/6 sm:grid-cols-3">{[["Captured leads", leadSnapshot.total], ["Grade A", leadSnapshot.gradeA], ["Unattended", leadSnapshot.unattended]].map(([label, value], index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className={`mt-3 block text-3xl ${label === "Unattended" && Number(value) ? "text-[#b53b33]" : ""}`}>{Number(value).toLocaleString("en-IN")}</strong></div>)}</div><div className="divide-y divide-black/5">{leadAwareness.slice(0, 8).map((item) => <div key={item.organizationId} className="grid gap-2 px-6 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><span><strong className="block text-sm">{item.organizationName}</strong><small className="mt-1 block text-[#68645c]">{item.total} total · A {item.gradeA} · B {item.gradeB} · C {item.gradeC}</small></span><span className={`text-xs font-bold ${item.unattended ? "text-[#b53b33]" : "text-[#17694f]"}`}>{item.unattended ? `${item.unattended} unattended` : "Team handling"}</span></div>)}{!leadAwareness.length ? <p className="px-6 py-10 text-center text-sm text-[#68645c]">No consented leads captured yet.</p> : null}</div><p className="border-t border-black/6 bg-[#f7f6f2] px-6 py-3 text-xs text-[#68645c]">Awareness only: visitor names, mobile numbers, requirements and conversations remain inside the client workspace.</p></section>

    <div className="grid gap-7 xl:grid-cols-[1.15fr_.85fr]">
      <section className="overflow-hidden border border-white/70 bg-white"><PanelHead eyebrow={`Support and operations · ${supportActions.length} active`} title="What requires action today" href="/admin/support" /><div className="divide-y divide-black/5">{supportActions.slice(0, 5).map((ticket) => <QueueRow key={ticket.id} tone={ticket.overdue || ticket.priority === "URGENT" ? "red" : "gold"} title={ticket.subject} copy={`${ticket.organizationName} · ${ticket.reference} · ${ticket.reason}`} href={`/admin/support/${ticket.id}`} />)}{paused ? <QueueRow tone="red" title={`${paused} customer account${paused === 1 ? "" : "s"} paused or suspended`} copy="Review payment or account status before service interruption continues." href="/admin/customers" /> : null}{failedMessages ? <QueueRow tone="red" title={`${failedMessages} failed message deliver${failedMessages === 1 ? "y" : "ies"}`} copy="Trace the affected customer and delivery channel." href="/admin/customers" /> : null}{!alerts ? <div className="px-6 py-12 text-center"><strong className="text-[#17694f]">No operational blocker</strong><p className="mt-2 text-sm text-[#68645c]">Continue onboarding or intelligence approval.</p></div> : null}</div></section>
      <section className="overflow-hidden border border-white/70 bg-[#f4f0e7]"><PanelHead eyebrow="Revenue continuity" title="Upcoming trial and billing dates" href="/admin/billing" /><div className="divide-y divide-black/6">{renewals.map(({organization,due}) => <Link key={organization.id} href={`/admin/customers/${organization.id}`} className="flex items-center justify-between gap-4 px-6 py-4 hover:bg-white/60"><span><strong className="block text-sm">{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.subscription?.plan.name || organization.plan} · {organization.subscription?.status || "Pending"}</small></span><span className="text-right text-xs font-bold text-[#6d5310]">{format(due)}</span></Link>)}{!renewals.length ? <p className="px-6 py-10 text-center text-sm text-[#68645c]">No upcoming billing date available.</p> : null}</div></section>
    </div>

    <div className="grid gap-7 xl:grid-cols-[.9fr_1.1fr]">
      <section className="overflow-hidden border border-white/70 bg-white"><PanelHead eyebrow="New customer intake" title="Recently created workspaces" href="/admin/customers" /><div className="divide-y divide-black/5">{organizations.slice(0,5).map((organization) => <Link key={organization.id} href={`/admin/customers/${organization.id}?onboarding=ai-bot`} className="grid gap-2 px-6 py-4 hover:bg-[#fbfaf7] sm:grid-cols-[1fr_auto] sm:items-center"><span><strong className="block text-sm">{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.botProfile?.personaName || organization.botProfile?.category || "Bot not selected"}</small></span><span className="text-xs font-bold text-[#6d5310]">{organization.botProfile?.status?.replaceAll("_"," ") || "DRAFT"} →</span></Link>)}{!organizations.length ? <p className="px-6 py-10 text-center text-sm text-[#68645c]">No customer workspace exists.</p> : null}</div></section>
      <section className="overflow-hidden border border-white/70 bg-[#0b0b0b] text-white"><div className="p-7 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d9ba58]">Launch discipline</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">A client moves through four gates.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2">{[["01","Owner verified","Identity and access"],["02","Intelligence approved","Knowledge and preview"],["03","Installation detected","Script, iframe or link"],["04","Release authorised","Evidence before live"]].map(([number,title,copy]) => <div key={number} className="border-l border-white/15 pl-4"><span className="text-xs font-bold text-[#d9ba58]">{number}</span><strong className="mt-2 block text-sm">{title}</strong><small className="mt-1 block text-white/45">{copy}</small></div>)}</div></div></section>
    </div>
  </main>;
}

function PanelHead({ eyebrow, title, href }: { eyebrow: string; title: string; href: string }) { return <div className="flex items-end justify-between gap-4 border-b border-black/6 px-6 py-5"><div><p className="product-eyebrow">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{title}</h2></div><Link href={href} className="text-xs font-bold text-[#6d5310]">Open →</Link></div>; }
function QueueRow({ tone, title, copy, href }: { tone: "red" | "gold"; title: string; copy: string; href: string }) { return <Link href={href} className="flex items-center gap-4 px-6 py-4 hover:bg-[#fbfaf7]"><span className={`h-2.5 w-2.5 rounded-full ${tone === "red" ? "bg-[#cf4d43]" : "bg-[#c79b23]"}`} /><span className="min-w-0 flex-1"><strong className="block text-sm">{title}</strong><small className="mt-1 block text-[#68645c]">{copy}</small></span><Icon name="arrow-right" className="text-[#8a6a16]" /></Link>; }
