import Link from "next/link";
import { MessagePolicyControl } from "@/components/admin/message-policy-control";
import { formatMoney } from "@/lib/billing-super-admin";
import { getMessageMatrix } from "@/lib/message-matrix";

export const dynamic = "force-dynamic";

export default async function MessageMatrixPage() {
  const matrix = await getMessageMatrix();
  const cards = [
    ["Messages", matrix.reduce((sum, item) => sum + item.usage.messages, 0)],
    ["AI replies", matrix.reduce((sum, item) => sum + item.usage.aiReplies, 0)],
    ["Negative ratings", matrix.reduce((sum, item) => sum + item.negative, 0)],
    ["Projected overage", formatMoney(matrix.reduce((sum, item) => sum + item.projectedOveragePaisa, 0))]
  ];
  return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-black/8 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="product-eyebrow">Usage, quality and restrictions</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Message Matrix</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#68645c]">Review every AI Bot, enforce its allowance and consider system-generated retention suggestions. Only Super Admin can approve free credits.</p></div><Link href="/admin/billing" className="rounded-full bg-[#101010] px-6 py-3 text-sm font-bold text-white">Open billing</Link></header>
    <section className="grid overflow-hidden border border-white/70 bg-white sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value], index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#777168]">{label}</p><strong className="mt-3 block text-3xl">{value}</strong></div>)}</section>
    <section className="overflow-hidden border border-white/70 bg-white"><div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">Per-customer report</p><h2 className="mt-2 text-2xl font-semibold">Performance and commercial allowance</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-left text-sm"><thead className="bg-[#f5f2eb] text-[10px] uppercase tracking-[.13em] text-[#68645c]"><tr>{["AI Bot", "Messages", "AI replies", "Safe resolution", "Helpful", "Escalated", "Restriction", "Projected charge", "Control"].map(label => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-black/5">{matrix.map(item => <tr key={item.organization.id}><td className="px-5 py-5"><strong>{item.organization.botProfile?.personaName || item.organization.name}</strong><small className="mt-1 block text-[#68645c]">{item.organization.name} · {item.subscription?.plan.name}</small></td><td className="px-5 py-5"><Usage used={item.usage.messages} limit={item.messageLimit} percent={item.messagePercent} /></td><td className="px-5 py-5"><Usage used={item.usage.aiReplies} limit={item.aiReplyLimit} percent={item.aiReplyPercent} /><small className="mt-1 block text-[#68645c]">{item.aiCredits.remaining.toLocaleString("en-IN")} extra left</small></td><td className="px-5 py-5 font-bold">{item.safeResolutionRate === null ? "No sample" : `${item.safeResolutionRate}%`}</td><td className="px-5 py-5">{item.helpfulRate === null ? "No rating" : `${item.helpfulRate}%`}<small className="block text-[#68645c]">{item.negative} negative</small></td><td className="px-5 py-5">{item.escalated}</td><td className="px-5 py-5"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${item.restriction === "HARD_STOP" ? "bg-[#fff0ee] text-[#a6322a]" : item.restriction === "APPROVED_OVERAGE" ? "bg-[#fff7dc] text-[#72560c]" : "bg-[#eaf7f1] text-[#17694f]"}`}>{item.restriction.replaceAll("_", " ")}</span></td><td className="px-5 py-5 font-bold">{formatMoney(item.projectedOveragePaisa)}</td><td className="px-5 py-5"><MessagePolicyControl organizationId={item.organization.id} messageLimit={item.messageLimit} aiReplyLimit={item.aiReplyLimit} messageRatePaisa={item.subscription?.messageOveragePaisa || 0} aiReplyRatePaisa={item.subscription?.aiReplyOveragePaisa || 0} overageApproved={item.subscription?.overageApproved || false} recommendation={item.freeCreditRecommendation} /></td></tr>)}{!matrix.length ? <tr><td colSpan={9} className="px-6 py-12 text-center text-[#68645c]">No active customer data.</td></tr> : null}</tbody></table></div></section>
    <p className="px-2 text-xs leading-5 text-[#777168]">Suggestions never grant credits automatically. Super Admin reviews usage, records the business reason and explicitly approves every grant.</p>
  </main>;
}

function Usage({ used, limit, percent }: { used: number; limit: number; percent: number }) {
  return <div className="w-36"><div className="flex justify-between text-xs"><strong>{used.toLocaleString("en-IN")}</strong><span>{limit.toLocaleString("en-IN")}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/7"><div className={`h-full ${percent >= 100 ? "bg-[#cf4d43]" : percent >= 80 ? "bg-[#c79b23]" : "bg-[#36a77a]"}`} style={{ width: `${Math.min(percent, 100)}%` }} /></div></div>;
}
