"use client";

import { useCallback, useEffect, useState } from "react";

type Ticket = { id:string; room:string; kind:"QUERY"|"COMPLAINT"; status:"NEW"|"IN_PROGRESS"|"RESOLVED"; priority:"URGENT"|"NORMAL"; owner:string|null; slaState:string; ageMinutes:number; latestMessage:string };

export function DepartmentMobileWorkspace({propertySlug,department,username}:{propertySlug:string;department:string;username:string}) {
  const [tickets,setTickets]=useState<Ticket[]>([]); const [selected,setSelected]=useState<Ticket|null>(null); const [note,setNote]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/hotelgpt-stay/cases?propertySlug=${encodeURIComponent(propertySlug)}`,{cache:"no-store"});const body=await response.json().catch(()=>null);if(response.ok){setTickets(body.cases||[]);setSelected(current=>current?(body.cases||[]).find((item:Ticket)=>item.id===current.id)||null:null);}else setError(body?.error||"Tickets could not be loaded.");},[propertySlug]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),12000);return()=>clearInterval(timer);},[load]);
  async function act(action:"TAKE"|"START"|"ADD_NOTE"|"SUBMIT_COMPLETION"){setBusy(true);setError("");const response=await fetch("/api/hotelgpt-stay/cases",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertySlug,caseId:selected?.id,action,note})});const body=await response.json().catch(()=>null);if(!response.ok)setError(body?.error||"Update failed.");else{setNote("");await load();}setBusy(false);}
  if(selected)return <main className="mx-auto min-h-dvh max-w-xl bg-[#f5f2e9] pb-28 text-[#17231c]"><header className="sticky top-0 z-10 border-b border-black/10 bg-[#10291f] px-4 py-4 text-white"><button onClick={()=>setSelected(null)} className="text-sm font-semibold text-[#e3c875]">← All tickets</button><p className="mt-3 text-xs font-bold uppercase tracking-[.16em] text-white/55">{department}</p><div className="mt-1 flex items-center justify-between"><h1 className="text-2xl font-bold">Room {selected.room}</h1><span className={`rounded-full px-3 py-1 text-xs font-bold ${selected.priority==="URGENT"?"bg-red-500 text-white":"bg-white/10"}`}>{selected.priority}</span></div></header><section className="space-y-4 p-4"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-black/45">Guest request</p><p className="mt-3 text-lg leading-7">{selected.latestMessage}</p><div className="mt-4 flex gap-2 text-xs font-bold"><span className="rounded-full bg-[#e8f3ed] px-3 py-1.5">{selected.status.replaceAll("_"," ")}</span><span className={`rounded-full px-3 py-1.5 ${selected.slaState==="OVERDUE"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-900"}`}>{selected.slaState.replaceAll("_"," ")} · {selected.ageMinutes}m</span></div></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="font-bold">Work update</p><p className="mt-1 text-sm text-black/55">Internal only. The front desk will confirm completion and reply to the guest.</p><textarea value={note} onChange={event=>setNote(event.target.value)} rows={4} maxLength={1000} placeholder="What was checked or completed?" className="mt-4 w-full rounded-xl border border-black/15 p-3 text-base"/>{error?<p role="alert" className="mt-3 text-sm font-semibold text-red-700">{error}</p>:null}</div></section><nav className="fixed inset-x-0 bottom-0 z-20 mx-auto grid max-w-xl grid-cols-2 gap-2 border-t border-black/10 bg-white p-3 pb-[max(.75rem,env(safe-area-inset-bottom))]"><button disabled={busy} onClick={()=>void act(selected.owner?"START":"TAKE")} className="min-h-12 rounded-xl border border-[#174f38] font-bold text-[#174f38]">{selected.owner?"Start work":"Take ticket"}</button><button disabled={busy||note.trim().length<3} onClick={()=>void act("SUBMIT_COMPLETION")} className="min-h-12 rounded-xl bg-[#174f38] font-bold text-white disabled:opacity-40">Submit completion</button><p className="col-span-2 text-center text-[11px] text-black/45">Signed in as {username}</p></nav></main>;
  return <main className="mx-auto min-h-dvh max-w-xl bg-[#f5f2e9] text-[#17231c]"><header className="sticky top-0 z-10 bg-[#10291f] px-5 pb-4 pt-[max(1rem,env(safe-area-inset-top))] text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e3c875]">InStay team</p><h1 className="mt-1 text-2xl font-bold">{department}</h1><p className="mt-1 text-sm text-white/60">{tickets.filter(item=>item.status!=="RESOLVED").length} open tickets · updates refresh automatically</p></header><section className="space-y-3 p-3">{error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}{tickets.length?tickets.map(ticket=><button key={ticket.id} onClick={()=>setSelected(ticket)} className="block w-full rounded-2xl border border-black/8 bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-black/40">{ticket.kind} · Room {ticket.room}</p><p className="mt-2 line-clamp-2 text-base font-semibold leading-6">{ticket.latestMessage}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[11px] font-bold ${ticket.slaState==="OVERDUE"?"bg-red-100 text-red-800":ticket.status==="RESOLVED"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{ticket.status.replaceAll("_"," ")}</span></div><p className="mt-3 text-xs text-black/50">{ticket.owner?`Owner: ${ticket.owner}`:"Unassigned"} · {ticket.ageMinutes}m</p></button>):<div className="rounded-2xl bg-white p-8 text-center"><p className="text-lg font-bold">No assigned tickets</p><p className="mt-2 text-sm text-black/50">New work routed by the front desk will appear here.</p></div>}</section></main>;
}
