"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type View = "overview" | "queries" | "complaints" | "resolved" | "reports";
type StayCase = { id:string; guestName:string; room:string; phone:string; kind:"QUERY"|"COMPLAINT"; status:"NEW"|"IN_PROGRESS"|"RESOLVED"; priority:"URGENT"|"NORMAL"; lastActivityAt:string; latestMessage:string };
const links = [["overview","Overview"],["queries","Queries"],["complaints","Complaints"],["resolved","Resolved"],["reports","Reports"],["access","QR & Access"]] as const;
export function InStayWorkspace({ propertySlug, view }: { propertySlug:string; view:View }) {
 const [cases,setCases]=useState<StayCase[]>([]),[metrics,setMetrics]=useState({total:0,queries:0,complaints:0,open:0,resolved:0,urgent:0}),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/hotelgpt-stay/cases?propertySlug=${encodeURIComponent(propertySlug)}`,{cache:"no-store"});const b=await r.json().catch(()=>null);if(r.ok){setCases(b.cases||[]);setMetrics(b.metrics);}else setNotice(b?.error||"In-stay cases could not be loaded.");},[propertySlug]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer);},[load]);
 const shown=useMemo(()=>cases.filter(item=>view==="queries"?item.kind==="QUERY"&&item.status!=="RESOLVED":view==="complaints"?item.kind==="COMPLAINT"&&item.status!=="RESOLVED":view==="resolved"?item.status==="RESOLVED":true),[cases,view]);
 async function act(item:StayCase,action:"START"|"RESOLVE"|"REOPEN"){const r=await fetch("/api/hotelgpt-stay/cases",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertySlug,caseId:item.id,action})});const b=await r.json().catch(()=>null);setNotice(r.ok?`Case ${action.toLowerCase()}d.`:b?.error||"Case could not be updated.");if(r.ok)await load();}
 return <div className="space-y-6"><nav className="flex gap-2 overflow-x-auto rounded-2xl border border-[var(--border)] bg-white p-2" aria-label="In-stay sections">{links.map(([key,label])=><Link key={key} href={key==="overview"?"/in-stay":`/in-stay/${key}`} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${view===key?"bg-[var(--gold-600)] text-white":"text-[var(--text-muted)] hover:bg-[#f7f3e7]"}`}>{label}</Link>)}</nav>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Open",metrics.open],["Queries",metrics.queries],["Complaints",metrics.complaints],["Urgent",metrics.urgent],["Resolved",metrics.resolved]].map(([label,value])=><div key={label} className="rounded-2xl border border-[var(--border)] bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</section>
 {notice?<p role="status" className="rounded-xl bg-[#fff7df] p-3 text-sm text-[#644d12]">{notice}</p>:null}
 {view==="reports"?<section className="rounded-2xl border border-[var(--border)] bg-white p-6"><h2 className="text-xl font-semibold">In-stay reports</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Reports use recorded guest cases only. No satisfaction score is inferred.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div><strong>{metrics.total}</strong><p className="text-sm text-[var(--text-muted)]">Total cases</p></div><div><strong>{metrics.complaints}</strong><p className="text-sm text-[var(--text-muted)]">Complaints</p></div><div><strong>{metrics.resolved}</strong><p className="text-sm text-[var(--text-muted)]">Resolved</p></div></div></section>:<section className="rounded-2xl border border-[var(--border)] bg-white p-6"><h2 className="text-xl font-semibold">{view==="overview"?"Current guest activity":view[0].toUpperCase()+view.slice(1)}</h2><div className="mt-5 space-y-3">{!shown.length?<p className="rounded-xl bg-[#f7f5ef] p-5 text-sm text-[var(--text-muted)]">No matching in-stay cases.</p>:shown.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[var(--border)] p-4"><div><div className="flex gap-2"><strong>{item.guestName} · Room {item.room}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${item.kind==="COMPLAINT"?"bg-red-100 text-red-700":"bg-blue-100 text-blue-700"}`}>{item.kind}</span>{item.priority==="URGENT"?<span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-800">URGENT</span>:null}</div><p className="mt-1 text-sm text-[var(--text-muted)]">{item.latestMessage||"Guest conversation started"}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{item.status} · {new Date(item.lastActivityAt).toLocaleString("en-IN")}</p></div><div className="flex gap-2">{item.status==="NEW"?<button onClick={()=>void act(item,"START")} className="rounded-md border px-3 py-2 text-xs font-bold">Start</button>:null}{item.status!=="RESOLVED"?<button onClick={()=>void act(item,"RESOLVE")} className="rounded-md bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Resolve</button>:<button onClick={()=>void act(item,"REOPEN")} className="rounded-md border px-3 py-2 text-xs font-bold">Reopen</button>}<Link href={`/team-inbox?journey=in-stay&lead=${item.id}`} className="rounded-md bg-black px-3 py-2 text-xs font-bold text-white">Open inbox</Link></div></article>)}</div></section>}</div>;
}
