"use client";
import {useState} from 'react';
import {clinicDates,clinicDoctors,clinicServices,clinicSlots,clinicSelectionValid} from '@/lib/demo-sandbox/clinic-availability';
export function ClinicDemoJourney({onChat}:{onChat:()=>void}){
 const [returning,setReturning]=useState(false),[showHistory,setShowHistory]=useState(false);
 const [step,setStep]=useState(0),[service,setService]=useState(''),[doctor,setDoctor]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[notice,setNotice]=useState('');
 const selected=clinicServices.find(s=>s.id===service), clinician=clinicDoctors.find(d=>d.id===doctor);
 const reset=()=>{setService('');setDoctor('');setDate('');setTime('');setStep(0);};
 const button='rounded-2xl border border-white/20 px-4 py-3 text-left text-base transition hover:border-amber-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber-300';
 const choose=(next:number)=>{setNotice('');setStep(next);};
 return <main className="flex min-h-screen flex-col rounded-3xl border border-amber-300/50 bg-[#101010] p-5 text-white">
 <header><a href="/ai-bot-demos" target="_blank" rel="noopener noreferrer" className="text-sm text-amber-200">← All AI Bot demos</a><p className="mt-5 text-sm text-amber-200">ClinicGPT · Interactive demo</p><h1 className="mt-2 text-2xl font-semibold">Aarogya Smile Clinic</h1><p className="mt-2 text-sm leading-6 text-white/65">Fictional clinic, doctors and availability. No real appointment or patient record is created.</p></header>
 <div className="mt-5 flex gap-2" aria-label="Booking progress">{['Service','Doctor','Date','Time','Review'].map((label,i)=><span key={label} className="flex-1 rounded-full px-1 py-2 text-center text-xs" style={{background:i===step?'#e8c866':'#252525',color:i===step?'#111':'#ddd'}}>{label}</span>)}</div>
 <section className="flex-1 py-6" aria-live="polite">
 {step===0&&<div className="mb-5 rounded-2xl border border-emerald-300/25 bg-emerald-300/5 p-4">{!returning?<><p className="mb-3 text-sm text-white/70">Returning patient experience</p><button className="text-left text-sm text-emerald-200 underline" onClick={()=>setReturning(true)}>Try fictional patient Asha’s profile</button><p className="mt-2 text-xs text-white/50">Demo selection only—not patient authentication.</p></>:<><h2 className="font-semibold">Welcome back, Asha.</h2><p className="mt-2 text-sm text-white/65">This is a fictional profile. Your real clinic would verify your identity before displaying this greeting.</p>{!showHistory?<button className="mt-3 text-sm text-emerald-200 underline" onClick={()=>setShowHistory(true)}>Show fictional last visit</button>:<div className="mt-3 text-sm"><p>Last demo visit: 20 August 2026</p><p>Dental consultation · Dr Meera Shah</p><p className="mt-2 text-white/60">No diagnosis or clinical notes are included in this showcase.</p><button className="mt-3 text-emerald-200 underline" onClick={()=>{setService('consult');setDoctor('meera');setDate('');setTime('');choose(2);}}>Choose a follow-up appointment</button><button className="ml-4 text-white/65 underline" onClick={()=>setShowHistory(false)}>Hide history</button></div>}<button className="mt-3 block text-xs text-white/60 underline" onClick={()=>{setReturning(false);setShowHistory(false);}}>Leave fictional profile</button></>}</div>}
 {notice&&<p role="status" className="mb-4 rounded-xl bg-white/10 p-3 text-sm">{notice}</p>}
 {step===0&&<><h2 className="mb-4 text-xl">What would you like help with?</h2><div className="grid gap-3">{clinicServices.map(s=><button key={s.id} className={button} onClick={()=>{setService(s.id);setDoctor('');setDate('');setTime('');choose(1);}}><strong className="block">{s.name}</strong><span className="text-sm text-white/60">{s.duration} min · Demo fee ₹{s.fee}</span></button>)}</div></>}
 {step===1&&<><h2 className="mb-4 text-xl">Choose a dentist</h2><div className="grid gap-3">{clinicDoctors.filter(d=>d.services.includes(service)).map(d=><button key={d.id} className={button} onClick={()=>{setDoctor(d.id);setDate('');setTime('');choose(2);}}><strong className="block">{d.name}</strong><span className="text-sm text-white/60">{d.specialty} · Fictional</span></button>)}</div></>}
 {step===2&&<><h2 className="mb-2 text-xl">Which day suits you?</h2><p className="mb-4 text-sm text-white/60">{clinician?.name} · Sunday closed · India time</p><div className="grid grid-cols-2 gap-3">{clinicDates().map(d=><button key={d} className={button} onClick={()=>{setDate(d);setTime('');choose(3);}}>{new Date(d+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',timeZone:'Asia/Kolkata'})}<span className="block text-sm text-emerald-300">{clinicSlots(service,doctor,d).length} demo slots</span></button>)}</div></>}
 {step===3&&<><h2 className="mb-2 text-xl">Available times</h2><p className="mb-4 text-sm text-white/60">{date} · {selected?.duration} minutes · IST. Occupied periods are excluded.</p><div className="grid grid-cols-3 gap-2">{clinicSlots(service,doctor,date).map(t=><button key={t} className={button} onClick={()=>{setTime(t);choose(4);}}>{t}</button>)}</div>{!clinicSlots(service,doctor,date).length&&<p>No slots remain for this selection. Choose another date or doctor.</p>}<button className="mt-5 text-sm text-amber-200 underline" onClick={()=>choose(2)}>Choose another date</button></>}
 {step>=4&&<><h2 className="mb-4 text-xl">{step===5?'Demo appointment confirmed':'Review your demo appointment'}</h2><dl className="space-y-3 rounded-2xl bg-white/5 p-5"><div><dt className="text-sm text-white/60">Service</dt><dd>{selected?.name} · {selected?.duration} minutes</dd></div><div><dt className="text-sm text-white/60">Dentist</dt><dd>{clinician?.name}</dd></div><div><dt className="text-sm text-white/60">Date and time</dt><dd>{date} at {time} IST</dd></div><div><dt className="text-sm text-white/60">Fictional fee</dt><dd>₹{selected?.fee} · Nothing to pay</dd></div></dl>{step===4?<><button className="mt-5 w-full rounded-full px-5 py-3 font-semibold" style={{background:'#e8c866',color:'#111'}} onClick={()=>{if(!clinicSelectionValid(service,doctor,date,time)){setNotice('That selection is no longer available. Please choose a new date.');setStep(2);return;}choose(5);}}>Confirm demo appointment</button><button className="mt-4 text-amber-200 underline" onClick={()=>choose(1)}>Change dentist or date</button></>:<><p className="mt-4 text-sm text-emerald-300">Reference DEMO-{date.replaceAll('-','')}-{doctor}-{time.replace(':','')}. Simulation only, for this session; no shared reservation, email or payment.</p><button className="mt-5 text-amber-200 underline" onClick={()=>choose(2)}>Change appointment</button><button className="ml-5 mt-5 text-red-300 underline" onClick={()=>{reset();setNotice('Demo appointment cancelled. No real booking was affected.');}}>Cancel demo appointment</button></>}</>}
 </section>
 <footer className="border-t border-white/10 pt-4">{step>0&&step<5&&<button className="mr-5 text-sm underline" onClick={()=>choose(step-1)}>← Back</button>}<button className="text-sm text-amber-200 underline" onClick={onChat}>Ask a clinic question instead</button><p className="mt-4 text-xs leading-5 text-white/50">Not medical advice. For urgent symptoms, contact local emergency services. Do not enter real patient information.</p></footer></main>;
}
