"use client";
import {useState} from 'react';
import {educationInstitutions,educationVisitDates,validEducationVisit,type EducationKind} from '@/lib/demo-sandbox/education-institutions';
type View='menu'|'admissions'|'fees'|'info'|'support'|'visit'|'review'|'done';
export function EducationDemoJourney(){
 const [kind,setKind]=useState<EducationKind|null>(null),[view,setView]=useState<View>('menu');
 const [programme,setProgramme]=useState(''),[year,setYear]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[notice,setNotice]=useState('');
 const institution=kind?educationInstitutions[kind]:null;
 const currentYear=new Date().getFullYear();
 const years=[`${currentYear}–${currentYear+1}`,`${currentYear+1}–${currentYear+2}`];
 const button='w-full rounded-2xl border border-white/25 px-4 py-4 text-left text-base hover:border-amber-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber-200';
 const go=(next:View)=>{setNotice('');setView(next);};
 const clear=()=>{setProgramme('');setYear('');setDate('');setTime('');};
 const pickProgramme=<label className="mb-4 block">{institution?.programLabel}<select value={programme} onChange={e=>{setProgramme(e.target.value);setTime('');}} className="mt-2 w-full rounded-xl p-3" style={{background:'#252525',color:'#fff'}}><option value="">Choose an option</option>{institution?.programmes.map(p=><option key={p} value={p}>{p}</option>)}</select></label>;
 const pickYear=<label className="mb-4 block">{kind==='coaching'?'Intake year':'Academic year'}<select value={year} onChange={e=>setYear(e.target.value)} className="mt-2 w-full rounded-xl p-3" style={{background:'#252525',color:'#fff'}}><option value="">Choose year</option>{years.map(y=><option key={y}>{y}</option>)}</select></label>;
 return <main className="flex min-h-screen flex-col rounded-3xl border border-amber-300/50 bg-[#101010] p-5 text-white">
 <header><a className="text-sm text-amber-200" href="/ai-bot-demos" target="_blank" rel="noopener noreferrer">← All AI Bot demos</a><p className="mt-5 text-sm text-amber-200">eduGPT · Interactive institution demo</p><h1 className="mt-2 text-2xl font-semibold">{institution?.name||'School, college or coaching?'}</h1><p className="mt-3 text-sm leading-6 text-white/65">Fictional information and appointment options. No admission, seat, scholarship or payment is confirmed.</p></header>
 <section className="flex-1 py-6" aria-live="polite">
 {notice&&<p role="status" className="mb-4 rounded-xl bg-white/10 p-3">{notice}</p>}
 {!kind?<div className="grid gap-3">{(Object.keys(educationInstitutions) as EducationKind[]).map(k=><button key={k} className={button} onClick={()=>{setKind(k);clear();go('menu');}}><strong className="block capitalize">{k}</strong><span className="text-sm text-white/60">{educationInstitutions[k].audience}</span></button>)}</div>:<>
 {view==='menu'&&<><h2 className="mb-4 text-xl">Welcome. How can we help?</h2><div className="grid gap-3">{([['admissions','Explore admissions'],['fees','Fees & documents'],['visit','Book a visit / counselling'],['info','Institution information'],['support','Existing student / parent support']] as [View,string][]).map(([v,label])=><button key={v} className={button} onClick={()=>go(v)}>{label} →</button>)}</div></>}
 {view==='admissions'&&<><h2 className="mb-4 text-xl">Explore admissions</h2>{pickProgramme}{pickYear}<p className="rounded-2xl bg-white/5 p-4 leading-7">{institution?.admissions}</p>{programme&&year&&<p className="mt-4 text-amber-200">Your interest: {programme}, {year}. This is not an application submission.</p>}<button className="mt-4 text-amber-200 underline" onClick={()=>go('visit')}>Discuss with admissions →</button></>}
 {view==='fees'&&<><h2 className="mb-4 text-xl">Illustrative fees & documents</h2><p className="rounded-2xl bg-white/5 p-4 leading-7">{institution?.fees}</p><h3 className="mt-5 font-semibold">Documents to prepare—not upload here</h3><ul className="my-3 list-disc space-y-2 pl-5">{institution?.documents.map(d=><li key={d}>{d}</li>)}</ul><p className="text-sm text-white/60">Real requirements and fees must be approved by the institution. Do not share identity documents in this public demo.</p></>}
 {view==='info'&&<><h2 className="mb-4 text-xl">Institution information</h2><p className="rounded-2xl bg-white/5 p-4 leading-7">{institution?.info}</p><button className="mt-5 text-amber-200 underline" onClick={()=>go('visit')}>Arrange a demo visit →</button></>}
 {view==='support'&&<><h2 className="mb-4 text-xl">Existing student / parent support</h2><p className="rounded-2xl bg-white/5 p-4 leading-7">{institution?.support}</p><p className="mt-4 text-sm text-amber-200">This showcase has no student login or record lookup. Contact your institution through its official portal; no support ticket has been sent.</p><button className="mt-5 text-amber-200 underline" onClick={()=>go('info')}>View public institution information</button></>}
 {view==='visit'&&<><h2 className="mb-4 text-xl">{institution?.visit}</h2>{pickProgramme}{pickYear}<label className="mb-4 block">Choose a demo date<select value={date} onChange={e=>{setDate(e.target.value);setTime('');}} className="mt-2 w-full rounded-xl p-3" style={{background:'#252525',color:'#fff'}}><option value="">Choose date</option>{educationVisitDates().map(d=><option key={d}>{d}</option>)}</select></label><p className="mb-3 text-sm text-white/60">Fixed fictional weekday slots · 30 minutes · IST</p><div className="flex gap-3">{institution?.times.map(t=><button key={t} className={button} aria-pressed={time===t} style={time===t?{background:'#e8c866',color:'#111'}:{}} onClick={()=>setTime(t)}>{t}</button>)}</div><button disabled={!year||!validEducationVisit(kind,programme,date,time)} className="mt-5 w-full rounded-full p-3 font-semibold disabled:opacity-40" style={{background:'#e8c866',color:'#111'}} onClick={()=>go('review')}>Review demo request</button></>}
 {(view==='review'||view==='done')&&<><h2 className="mb-4 text-xl">{view==='review'?'Review your visit request':'Demo request prepared'}</h2><div className="space-y-3 rounded-2xl bg-white/5 p-5"><p>{institution?.visit}</p><p>{programme} · {year}</p><p>{date} · {time} IST</p></div>{view==='review'?<button className="mt-5 w-full rounded-full p-3 font-semibold" style={{background:'#e8c866',color:'#111'}} onClick={()=>{if(!years.includes(year)||!validEducationVisit(kind,programme,date,time)){setView('visit');setNotice('Please refresh the expired or invalid selection.');return;}go('done');}}>Confirm simulated request</button>:<p className="mt-4 text-emerald-200">Simulation complete. No staff notification, calendar booking, admission or seat allocation occurred.</p>}<div className="mt-5 flex gap-5"><button className="text-amber-200 underline" onClick={()=>go('visit')}>Change details</button><button className="text-red-300 underline" onClick={()=>{clear();setView('menu');setNotice('Demo request cancelled. No real record was affected.');}}>Cancel request</button></div></>}
 </>}
 </section><footer className="border-t border-white/10 pt-4">{kind&&<div className="flex flex-wrap gap-4">{view!=='menu'&&<button className="text-sm text-amber-200 underline" onClick={()=>go('menu')}>← Main menu</button>}<button className="text-sm text-white/70 underline" onClick={()=>{setKind(null);clear();go('menu');}}>Change institution</button></div>}<p className="mt-4 text-xs leading-5 text-white/50">Public information only. Never enter student records or personal documents. Session-only demo; refreshing resets selections.</p></footer>
 </main>;
}
