"use client";
import {useState} from 'react';
import {addNights,hospitalityDates,hotelAvailability,diningAvailability,hospitalityChoiceValid} from '@/lib/demo-sandbox/hospitality-availability';
export function HospitalityDemoJourney({mode,onChat}:{mode:'hotel'|'dine';onChat:()=>void}){
 const hotel=mode==='hotel';
 const [step,setStep]=useState(0),[date,setDate]=useState(''),[nights,setNights]=useState(1),[guests,setGuests]=useState(2),[choice,setChoice]=useState(''),[notice,setNotice]=useState('');
 const rooms=hotelAvailability(date,nights,guests),slots=diningAvailability(date,guests),room=rooms.find(r=>r.id===choice),slot=slots.find(s=>s.time===choice);
 const btn='rounded-2xl border border-white/25 px-4 py-3 text-left text-base hover:border-amber-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber-200';
 const go=(n:number)=>{setStep(n);setNotice('');};
 const labels=['Date',hotel?'Stay & guests':'Party size',hotel?'Room':'Time','Review'];
 const reset=()=>{setStep(0);setDate('');setChoice('');setNotice(`Demo ${hotel?'stay':'reservation'} cancelled. No real booking was affected.`);};
 return <main className="flex min-h-screen flex-col rounded-3xl border border-amber-300/50 bg-[#101010] p-5 text-white">
 <header><a href="/ai-bot-demos" target="_blank" rel="noopener noreferrer" className="text-sm text-amber-200">← All AI Bot demos</a><p className="mt-5 text-sm text-amber-200">{hotel?'HotelGPT':'DineGPT'} · Interactive demo</p><h1 className="mt-2 text-2xl font-semibold">{hotel?'Casa Aurelia Resort':'Saffron Table'}</h1><p className="mt-2 text-sm leading-6 text-white/65">Fictional {hotel?'rooms and rates':'tables and availability'}. This session is a simulation, not a real reservation.</p></header>
 <ol aria-label="Booking progress" className="mt-5 flex flex-wrap gap-2">{labels.map((l,i)=><li key={l} aria-current={step===i?'step':undefined} className="rounded-full px-3 py-2 text-sm" style={{background:step===i?'#e8c866':'#252525',color:step===i?'#111':'#ddd'}}>{i+1}. {l}</li>)}</ol>
 <section className="flex-1 py-6" aria-live="polite">{notice&&<p role="status" className="mb-4 rounded-xl bg-white/10 p-3 text-sm">{notice}</p>}
 {step===0&&<><h2 className="mb-4 text-xl">{hotel?'When would you like to check in?':'Which evening suits you?'}</h2><div className="grid grid-cols-2 gap-3">{hospitalityDates().map(d=><button key={d} className={btn} onClick={()=>{setDate(d);setChoice('');go(1);}}>{new Date(d+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',timeZone:'Asia/Kolkata'})}</button>)}</div><p className="mt-4 text-sm text-white/60">{hotel?'Check-in 2 PM · Check-out 11 AM':'Dinner 7–11 PM · Tables reserved for 90 minutes'} · IST</p></>}
 {step===1&&<>{hotel&&<><h2 className="mb-3 text-xl">How long will you stay?</h2><div className="mb-6 flex gap-2">{[1,2,3].map(n=><button key={n} aria-pressed={nights===n} className={btn} style={nights===n?{background:'#e8c866',color:'#111'}:{}} onClick={()=>{setNights(n);setChoice('');}}>{n} {n===1?'night':'nights'}</button>)}</div></>}<h2 className="mb-3 text-xl">{hotel?'How many guests in one room?':'How many people are dining?'}</h2><div className="flex flex-wrap gap-2">{(hotel?[1,2,3,4]:[1,2,3,4,5,6,8]).map(n=><button key={n} aria-pressed={guests===n} className={btn} style={guests===n?{background:'#e8c866',color:'#111'}:{}} onClick={()=>{setGuests(n);setChoice('');}}>{n}</button>)}</div><button className="mt-6 w-full rounded-full px-5 py-3 font-semibold" style={{background:'#e8c866',color:'#111'}} onClick={()=>go(2)}>Check demo availability →</button></>}
 {step===2&&<><h2 className="mb-2 text-xl">{hotel?'Rooms available for your full stay':'Available table times'}</h2><p className="mb-4 text-sm text-white/60">{date}{hotel?` → ${addNights(date,nights)} · ${nights} nights`:''} · {guests} guests</p><div className="grid gap-3">{hotel?rooms.map(r=><button key={r.id} className={btn} onClick={()=>{setChoice(r.id);go(3);}}><strong className="block">{r.name}</strong><span className="block text-sm text-white/65">{r.description} · Up to {r.guests} guests</span><span className="mt-2 block text-amber-200">₹{r.rate.toLocaleString('en-IN')}/night · ₹{r.total.toLocaleString('en-IN')} demo total</span></button>):slots.map(s=><button key={s.time} className={btn} onClick={()=>{setChoice(s.time);go(3);}}><strong>{s.time} IST</strong><span className="ml-3 text-sm text-white/65">Table for up to {s.seats}</span></button>)}</div>{!(hotel?rooms.length:slots.length)&&<div className="rounded-2xl bg-white/5 p-4"><p>No {hotel?'room fits the whole stay':'table fits this party size'} in the demo inventory.</p><p className="mt-2 text-sm text-white/65">{!hotel&&guests>6?'For parties over six, a real restaurant would arrange a staff-assisted group reservation. No staff request has been sent.':'Try another date below; suggestions are checked against the same inventory.'}</p></div>}{!(hotel?rooms.length:slots.length)&&<div className="mt-4 grid gap-2">{hospitalityDates().filter(d=>d!==date&&(hotel?hotelAvailability(d,nights,guests).length:diningAvailability(d,guests).length)).slice(0,3).map(d=><button key={d} className={btn} onClick={()=>{setDate(d);setChoice('');}}>{d} · Available alternative</button>)}</div>}<button className="mt-5 text-sm text-amber-200 underline" onClick={()=>go(0)}>Change date</button><button className="ml-5 text-sm text-amber-200 underline" onClick={()=>go(1)}>Change {hotel?'stay or guests':'party size'}</button></>}
 {step>=3&&<><h2 className="mb-4 text-xl">{step===4?'Demo confirmation':'Review before confirming'}</h2><div className="space-y-3 rounded-2xl bg-white/5 p-5"><p>{hotel?room?.name:`Table ${slot?.table} · ${choice} IST`}</p><p>{date}{hotel?` → ${addNights(date,nights)}`:''}</p><p>{guests} guests{hotel?` · ${nights} nights`: ' · 90 minutes'}</p>{hotel&&<p>Demo total ₹{room?.total.toLocaleString('en-IN')} · Breakfast included</p>}<p className="text-sm text-white/60">Nothing to pay. No real inventory is held.</p></div>{step===3?<><button className="mt-5 w-full rounded-full px-5 py-3 font-semibold" style={{background:'#e8c866',color:'#111'}} onClick={()=>{if(!hospitalityChoiceValid(mode,date,nights,guests,choice)){setNotice('Availability changed or the date expired. Please choose again.');setStep(0);return;}go(4);}}>Confirm demo {hotel?'stay':'table'}</button><button className="mt-4 text-amber-200 underline" onClick={()=>{setChoice('');go(0);}}>Change details</button></>:<><p className="mt-4 text-sm text-emerald-300">DEMO-{mode.toUpperCase()}-{date.replaceAll('-','')}-{choice.replace(':','')}. Session-only simulation; no payment, email or shared reservation.</p><button className="mt-5 text-amber-200 underline" onClick={()=>{setChoice('');go(0);}}>Change booking</button><button className="ml-5 text-red-300 underline" onClick={reset}>Cancel demo booking</button></>}</>}
 </section><footer className="border-t border-white/10 pt-4">{step>0&&step<4&&<button className="mr-5 text-sm underline" onClick={()=>go(step-1)}>← Back</button>}<button className="text-sm text-amber-200 underline" onClick={onChat}>Ask a {hotel?'hotel':'restaurant'} question instead</button><p className="mt-4 text-sm text-white/50">Use fictional details only.{!hotel?' Allergy questions require staff confirmation.':''}</p></footer></main>;
}
