"use client";
import { useEffect, useState, type FormEvent } from "react";
import { WebsiteBotEmbed } from "@/components/website-bot/website-bot-embed";
import type { WidgetMenuConfig } from "@/lib/widget-menu";

type State = "FORM" | "PENDING" | "APPROVED" | "REJECTED" | "REVOKED" | "EXPIRED";
export function HotelGptResidentEntry({ slug, propertyName, botName, themeColor, widgetTheme, logoUrl, menu }: { slug: string; propertyName: string; botName: string; themeColor: string; widgetTheme: "dark" | "light" | "system"; logoUrl: string; menu: WidgetMenuConfig }) {
  const [state, setState] = useState<State>("FORM"); const [requestToken, setRequestToken] = useState(""); const [stayToken, setStayToken] = useState(""); const [validUntil, setValidUntil] = useState(""); const [room, setRoom] = useState(""); const [guestName, setGuestName] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [resolutionNotice,setResolutionNotice]=useState("");
  useEffect(() => { const saved = localStorage.getItem(`hotelgpt-access:${slug}`); if (saved) { setRequestToken(saved); setState("PENDING"); } }, [slug]);
  useEffect(() => {
    if (!requestToken || state === "APPROVED") return; let stopped = false; let timer: ReturnType<typeof setTimeout>;
    async function check() { const r = await fetch(`/api/public/hotelgpt-stay/${encodeURIComponent(slug)}/session`, { headers: { Authorization: `Bearer ${requestToken}` }, cache: "no-store" }); const b = await r.json().catch(() => null); if (stopped) return; if (r.ok && b?.status === "APPROVED") { setStayToken(b.stayAccessToken); setValidUntil(b.validUntil); setRoom(b.roomNumber); setGuestName(b.guestName); setState("APPROVED"); } else if (r.ok && ["PENDING", "REJECTED", "REVOKED", "EXPIRED"].includes(b?.status)) setState(b.status); else if ([401, 404].includes(r.status)) { localStorage.removeItem(`hotelgpt-access:${slug}`); setState("EXPIRED"); } if (!stopped && (b?.status === "PENDING" || !r.ok && ![401, 404].includes(r.status))) timer = setTimeout(check, 5000); }
    void check(); return () => { stopped = true; clearTimeout(timer); };
  }, [requestToken, slug, state]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); data.checkOut = new Date(String(data.checkOut)).toISOString(); const r = await fetch(`/api/public/hotelgpt-stay/${encodeURIComponent(slug)}/session`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const b = await r.json().catch(() => null); if (r.ok && b?.requestToken) { localStorage.setItem(`hotelgpt-access:${slug}`, b.requestToken); setRequestToken(b.requestToken); setState("PENDING"); } else setError(b?.error || "Access request could not be submitted."); setLoading(false); }
  async function updateResolution(action:"CONFIRM_RESOLUTION"|"REOPEN"){setResolutionNotice("");const r=await fetch(`/api/public/hotelgpt-stay/${encodeURIComponent(slug)}/session`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${stayToken}`},body:JSON.stringify({action})});const b=await r.json().catch(()=>null);setResolutionNotice(r.ok?(action==="CONFIRM_RESOLUTION"?"Thank you. The front desk has been notified that this is resolved.":"Your request is open again and visible to the front desk."):b?.error||"The request could not be updated.");}
  if (state === "APPROVED") return <main className="min-h-dvh bg-[#050505] px-3 py-4 sm:px-6 sm:py-8"><div className="mx-auto max-w-[460px]"><div className="mb-3 rounded-xl border border-emerald-400/30 bg-emerald-950 px-4 py-3 text-sm text-emerald-50"><strong>Welcome, {guestName} · Room {room}</strong><br/>Your In-stay Assistant is ready until {new Date(validUntil).toLocaleString("en-IN")}</div><WebsiteBotEmbed slug={slug} botName={botName} welcomeMessage={`Welcome, ${guestName}. How can ${propertyName} help with your stay today?`} themeColor={themeColor} widgetTheme={widgetTheme} logoUrl={logoUrl} menu={menu} stayAccessToken={stayToken} residentMode /><section className="mt-3 rounded-xl border border-white/15 bg-white/5 p-4 text-white"><p className="text-sm font-semibold">Has the hotel completed your request?</p><div className="mt-3 flex gap-2"><button onClick={()=>void updateResolution("CONFIRM_RESOLUTION")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold">Yes, resolved</button><button onClick={()=>void updateResolution("REOPEN")} className="rounded-lg border border-white/25 px-3 py-2 text-xs font-bold">I still need help</button></div>{resolutionNotice?<p role="status" className="mt-3 text-xs text-white/75">{resolutionNotice}</p>:null}</section></div></main>;
  if (state !== "FORM") { const pending = state === "PENDING"; return <main className="grid min-h-dvh place-items-center bg-[#06141c] p-4 text-white"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0b2532] p-8 text-center"><div className={`mx-auto grid size-16 place-items-center rounded-full text-3xl ${pending ? "bg-amber-400 text-slate-900" : "bg-red-600"}`}>{pending ? "…" : "×"}</div><h1 className="mt-5 text-2xl font-semibold">{pending ? "Awaiting front desk approval" : state === "REJECTED" ? "Request not approved" : "In-stay access ended"}</h1><p className="mt-3 text-sm leading-6 text-white/70">{pending ? "Your stay details were submitted. After approval, scan the same QR on this phone to return directly to your In-stay Assistant." : state === "REJECTED" ? "Please contact the front desk to check or correct your stay details." : "Protected in-stay services and communication are no longer accessible. Please contact the hotel directly if you need assistance."}</p>{!pending ? <button className="mt-6 rounded-xl bg-white px-5 py-3 font-bold text-slate-900" onClick={() => { localStorage.removeItem(`hotelgpt-access:${slug}`); setRequestToken(""); setState("FORM"); }}>Submit a new request</button> : null}</section></main>; }
  return <main className="grid min-h-dvh place-items-start bg-[#06141c] px-4 py-6 text-white sm:place-items-center sm:py-10"><section className="w-full min-w-0 max-w-md overflow-hidden rounded-3xl border border-white/10 bg-[#0b2532] p-6 shadow-2xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e7c66c]">HotelGPT · In-stay guest access</p><h1 className="mt-3 text-3xl font-semibold">Welcome to {propertyName}</h1><p className="mt-3 text-sm leading-6 text-white/70">Enter the same details provided during hotel check-in. Access starts only after front-desk approval.</p><form className="mt-7 space-y-4" onSubmit={submit}><label className="block min-w-0 text-sm font-semibold">Guest name<input name="guestName" required maxLength={100} autoComplete="name" className="mt-2 block min-w-0 w-full max-w-full rounded-xl bg-white px-4 py-3 text-black" /></label><label className="block min-w-0 text-sm font-semibold">Phone number<input name="phoneNumber" required type="tel" maxLength={16} autoComplete="tel" className="mt-2 block min-w-0 w-full max-w-full rounded-xl bg-white px-4 py-3 text-black" /></label><label className="block min-w-0 text-sm font-semibold">Room number<input name="roomNumber" required maxLength={24} autoComplete="off" className="mt-2 block min-w-0 w-full max-w-full rounded-xl bg-white px-4 py-3 text-black" /></label><div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-3"><label className="block min-w-0 text-sm font-semibold">Check-in<input name="checkIn" type="date" required className="mt-2 block min-w-0 w-full max-w-full rounded-xl bg-white px-3 py-3 text-black" /></label><label className="block min-w-0 text-sm font-semibold">Checkout date & time<input name="checkOut" type="datetime-local" required className="mt-2 block min-w-0 w-full max-w-full rounded-xl bg-white px-3 py-3 text-black" /></label></div>{error ? <p role="alert" className="rounded-xl bg-red-950/60 p-3 text-sm">{error}</p> : null}<button disabled={loading} className="w-full rounded-xl bg-[#e7c66c] px-4 py-3 font-bold text-[#10202a] disabled:opacity-60">{loading ? "Submitting…" : "Request In-stay Access"}</button></form><p className="mt-5 text-xs leading-5 text-white/55">Approval creates access only for this property and approved stay window. Do not share passwords, PINs, door codes, payment information or identity documents in chat.</p></section></main>;
}
