import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getCurrentUser } from "@/lib/auth-server";
import { CASTLE_PILOT_TENANT, getPilotReport, reviewPilotObservation, setPilotPolicy, type PilotReviewVerdict } from "@/lib/typesafe-pilot-store";
import { evaluateTypesafePromotion } from "@/lib/typesafe-promotion-gates";

export const dynamic = "force-dynamic";
async function disablePilot() { "use server"; const user=await getCurrentUser(); if(!user||user.role!=="admin")throw Error("Super Admin required"); await setPilotPolicy(CASTLE_PILOT_TENANT,{enabled:false,expiresAt:new Date().toISOString(),dailyLimit:20},user.username); revalidatePath("/admin/typesafe"); }
async function reviewObservation(formData:FormData) { "use server"; const user=await getCurrentUser(); if(!user||user.role!=="admin")throw Error("Super Admin required"); await reviewPilotObservation(CASTLE_PILOT_TENANT,String(formData.get("observationId")||""),String(formData.get("verdict")||"") as PilotReviewVerdict,String(formData.get("rationale")||""),user.username); revalidatePath("/admin/typesafe"); }

export default async function TypeSafePilotPage(){
 const user=await getCurrentUser(); if(!user||user.role!=="admin")redirect("/login");
 const report=await getPilotReport(); const policy=report.policy as {expiresAt?:string;dailyLimit?:number}|null;
 const configured=process.env.TYPESAFE_ACTION_GATEWAY_ENABLED==="true"&&process.env.TYPESAFE_MODE==="shadow"&&Boolean(process.env.TYPESAFE_API_KEY)&&(process.env.TYPESAFE_SHADOW_ORGANIZATIONS||"").split(",").includes(CASTLE_PILOT_TENANT);
 const promotion=evaluateTypesafePromotion({liveObservations:report.count,unavailable:report.unavailable,p95Ms:report.p95Ms,humanReviewedLiveDecisions:report.reviewed,crossTenantRegressions:0,durableQuotaVerified:true,disableVerified:true,failureFallbackVerified:true,synthetic:null});
 return <main className="mx-auto max-w-6xl space-y-6 p-8">
  <header><p className="product-eyebrow">Super Admin · controlled evaluation</p><h1 className="mt-2 text-3xl font-semibold">TypeSafe shadow pilot</h1><p className="mt-3 text-sm text-stone-600">Castle Mandawa only. Customer text stays in existing internal evidence and is never copied to TypeSafe telemetry or sent to TypeSafe.</p></header>
  <section className="rounded-2xl bg-stone-950 p-6 text-white"><h2 className="text-xl">{report.active&&configured?"Shadow enabled":"Off / expired / not configured"}</h2><p className="mt-2">Expiry: {policy?.expiresAt||"Not configured"} · Daily cap: {policy?.dailyLimit||0}</p><p className="mt-2 text-sm text-stone-300">Database reservations survive restarts. An already-dispatched request may finish after disable.</p><form action={disablePilot}><button className="mt-5 rounded-lg bg-red-700 px-5 py-3 font-semibold">Disable pilot now</button></form></section>
  <section className="grid gap-4 sm:grid-cols-5">{[["Observations",report.count],["Human reviewed",report.reviewed],["Unavailable",report.unavailable],["p95 latency",report.p95Ms===null?"No data":`${report.p95Ms} ms`],["Input / output tokens",`${report.inputTokens} / ${report.outputTokens}`]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-stone-600">{label}</p><strong className="mt-2 block text-xl">{value}</strong></div>)}</section>
  <p className="rounded-xl border bg-amber-50 p-4 text-sm">{report.assessment}. Label agreement is not accuracy. Estimated usage cost: ${report.estimatedUsd.toFixed(6)}. {report.costStatus} <a className="underline" href={report.priceSource} target="_blank" rel="noreferrer">Pricing source</a>.</p>
  <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Ten-step promotion review</h2><p className="mt-2 text-sm text-stone-600">Step 9 needs every gate plus human approval. Step 10 requires a separate production decision.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{promotion.gates.map(gate=><div key={gate.id} className={`rounded-lg border p-4 ${gate.passed?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><strong className="text-sm">{gate.passed?"PASS":"BLOCKED"} · {gate.label}</strong><p className="mt-1 text-xs text-stone-600">{gate.detail}</p></div>)}</div></section>
  <section className="space-y-4"><h2 className="text-xl font-semibold">Independent decision review</h2>{report.samples.map(sample=>{const data=sample as Record<string,unknown>;return <article key={sample.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><strong>{String(data.intent||"UNKNOWN")} · {String(data.confidence??"—")}</strong><span className="text-xs text-stone-500">{sample.at}</span></div>{sample.evidence?<><p className="mt-4 text-sm"><b>Customer:</b> {sample.evidence.question}</p><p className="mt-2 text-sm"><b>Served answer:</b> {sample.evidence.answer}</p></>:<p className="mt-4 text-sm text-amber-700">No review linkage is available for this legacy observation.</p>}{sample.review?<p className="mt-4 rounded-lg bg-stone-100 p-3 text-sm"><b>{sample.review.verdict}</b> · {sample.review.rationale} · {sample.review.reviewer}</p>:sample.evidence?<form action={reviewObservation} className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="observationId" value={sample.id}/><select name="verdict" required className="rounded-lg border p-2"><option value="">Choose verdict</option><option value="CORRECT">Correct</option><option value="INCORRECT">Incorrect</option><option value="UNRESOLVED">Unresolved</option></select><input name="rationale" minLength={12} maxLength={1000} required placeholder="Independent review rationale" className="rounded-lg border p-2"/><button className="rounded-lg bg-stone-950 px-4 py-2 font-semibold text-white">Save review</button></form>:null}</article>})}{!report.count?<p className="rounded-xl border bg-white p-6">No live observations yet.</p>:null}</section>
 </main>;
}
