"use client";

import { useState } from "react";

const registerUrl = "https://app.aifrogi.com/register?source=pricing";
export function AiBotPricing() {
  const [annual, setAnnual] = useState(false);

  return <>
    <section className="bg-[#050505] px-5 py-20 text-center text-white sm:px-8 sm:py-24">
      <div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#e2c66d]">AI Bot pricing</p><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-6xl">Start small. Prove value. Scale with control.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/65">One governed AI Business Bot, approved knowledge, human handover and measurable conversations. Connector and provider costs remain transparent.</p></div>
    </section>

    <section id="plans" className="bg-[#fbfaf7] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl">
      <div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="product-eyebrow">Simple foundation</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Choose how you begin.</h2><p className="mt-4 leading-7 text-[var(--text-muted)]">Starter is an introductory launch offer for one AI Bot. Pay ₹499 monthly or ₹4,999 yearly and save ₹989. Included allowances are published below; third-party charges remain separate.</p></div><div className="inline-flex w-fit rounded-full border border-black/10 bg-white p-1" aria-label="Starter billing period"><button type="button" aria-pressed={!annual} onClick={() => setAnnual(false)} className={`rounded-full px-5 py-2 text-sm ${!annual ? "bg-[#8a6a16] font-semibold text-white" : "text-[#404040]"}`}>₹499 monthly</button><button type="button" aria-pressed={annual} onClick={() => setAnnual(true)} className={`rounded-full px-5 py-2 text-sm ${annual ? "bg-[#8a6a16] font-semibold text-white" : "text-[#404040]"}`}>₹4,999 yearly · save ₹989</button></div></div>
      <div className="mt-10 grid gap-5 lg:grid-cols-3">
        <Plan title="15-day trial" price="₹0" note="No card required" copy="Validate the bot on your approved knowledge before subscribing." features={["One demo AI Bot", "Website widget and shareable link", "Approved knowledge setup", "Human-contact handover", "Pauses after day 15", "Workspace data remains preserved under our retention and deletion terms"]} cta="Start free trial" href={registerUrl} />
        <Plan featured title="Starter" price={annual ? "₹4,999" : "₹499"} note={annual ? "per year · billed annually" : "per month · billed monthly"} copy="For a small business operating one focused customer journey." features={["One live AI Business Bot", "Widget and standalone link", "Up to 3 team users", "Knowledge and persona updates", "Conversation evidence and feedback", "Published usage allowances", "Email support"]} cta="Start trial with Starter selected" href={`${registerUrl}&plan=starter&billing=${annual ? "yearly" : "monthly"}`} secondary={{ label: "Already have an account? Pay securely", href: `https://app.aifrogi.com/billing?checkout=1&plan=${annual ? "AI_STARTER_YEARLY" : "AI_STARTER_MONTHLY"}` }} />
        <Plan title="Custom / Enterprise" price="Let’s talk" note="Scope-based proposal" copy="For multiple bots, locations, complex connectors, governance or higher usage." features={["Multi-bot or multi-location", "Custom workflows and connectors", "Advanced roles and reporting", "Security and rollout planning", "Priority support options"]} cta="Email info@aifrogi.com" href="mailto:info@aifrogi.com?subject=AiFrogi%20Enterprise%20Plan" secondary={{ label: "Call +91-7410582898", href: "tel:+917410582898" }} />
      </div>
      <div id="plan-limits" className="mt-8 grid gap-4 rounded-2xl border border-black/10 bg-white p-6 md:grid-cols-[.7fr_1fr_1fr]"><div><p className="product-eyebrow">Published allowances</p><h3 className="mt-2 text-xl font-semibold">No surprise cap.</h3><p className="mt-2 text-sm leading-6 text-[#666]">Usage is visible in the customer dashboard. At the limit, AI replies pause safely while existing data and human-contact options remain available. Clients can buy a disclosed prepaid credit pack; there is no automatic overage charge.</p></div><Allowance title="15-day trial" values={["100 AI replies", "500 total messages", "250 saved contacts", "Up to 2 team users"]} /><Allowance title="Starter launch allowance" values={["1,000 AI replies", "5,000 total messages", "2,000 saved contacts", "Up to 3 team users", "Prepaid extra credits available"]} /></div>
      <div className="mt-8"><p className="product-eyebrow">Prepaid AI reply credits</p><h3 className="mt-2 text-2xl font-semibold">Buy more only when you need them.</h3><p className="mt-2 text-sm text-[var(--text-muted)]">Available to active customers, valid for 90 days and added immediately after verified payment. Prices exclude applicable taxes.</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["500", "₹399"], ["1,500", "₹999"], ["5,000", "₹2,999"]].map(([credits, price]) => <div key={credits} className="rounded-xl border border-black/10 bg-white p-5"><strong className="text-2xl">{credits}</strong><span className="block text-sm text-[#666]">AI reply credits</span><span className="mt-4 block text-xl font-semibold">{price}</span></div>)}</div><a href="https://app.aifrogi.com/billing" className="mt-5 inline-flex rounded-lg bg-[#101010] px-5 py-3 text-sm font-semibold text-white">Buy credits securely</a></div>
    </div></section>

    <section className="bg-white px-5 py-6 text-center"><p className="text-sm text-stone-600">No automatic top-up or silent overage. Super Admin may also grant audited free credits for approved support, pilot or service-recovery reasons.</p><a href="https://app.aifrogi.com/billing" className="mt-3 inline-block text-sm underline">View usage and billing</a></section>
    <section className="bg-white px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-4 rounded-2xl border border-black/10 bg-[#fbfaf7] p-6 sm:flex-row sm:items-center sm:p-8"><p className="max-w-4xl leading-7 text-[#404040]"><strong className="text-[#101010]">Need calendar, CRM, payment, ecommerce or PMS integration?</strong> Connector pricing is quoted separately based on your requirements.</p><a href="mailto:info@aifrogi.com?subject=AiFrogi%20Connector%20Requirement" className="shrink-0 font-semibold text-[#6d5310] underline underline-offset-4">Contact us →</a></div></section>

    <section className="bg-[#f3e5b5] px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs uppercase tracking-[.18em] text-[#6d5310]">Before payment</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em]">Clear commercial terms.</h2></div><div className="grid gap-5 text-sm leading-6 text-[#404040] sm:grid-cols-2"><p><strong className="block text-[#101010]">Subscriptions</strong>Paid in advance and renew until cancelled. Cancellation stops the next renewal; access continues to the paid-period end.</p><p><strong className="block text-[#101010]">Connector projects</strong>Scope, milestones, dependencies and provider access are confirmed before work begins.</p><p><strong className="block text-[#101010]">Refunds</strong>Duplicate or erroneous payments are reviewed. Activated subscriptions and completed work are generally non-refundable, subject to applicable law.</p><p><strong className="block text-[#101010]">Allowances and extras</strong>Current limits are published above. Higher usage remains stopped unless a customer-approved unit rate is recorded; taxes, provider fees and custom work remain separate.</p></div><div className="lg:col-start-2"><a href="/terms-of-service" className="inline-flex rounded-lg bg-[#8a6a16] px-5 py-3 text-sm font-semibold text-white">Read full payment and service terms</a></div></div></section>
  </>;
}

function Allowance({ title, values }: { title: string; values: string[] }) {
  return <div className="rounded-xl bg-[#fbfaf7] p-5"><h4 className="font-semibold">{title}</h4><ul className="mt-3 grid gap-2 text-sm text-[#5f5f5f] sm:grid-cols-2 md:grid-cols-1">{values.map((value) => <li key={value} className="flex gap-2"><span className="text-[#8a6a16]">•</span>{value}</li>)}</ul></div>;
}

function Plan({ title, price, note, copy, features, cta, href, featured = false, secondary }: { title: string; price: string; note: string; copy: string; features: string[]; cta: string; href: string; featured?: boolean; secondary?: { label: string; href: string } }) {
  return <article className={`flex flex-col rounded-2xl border bg-white p-7 ${featured ? "border-[#8a6a16] shadow-[0_20px_60px_rgba(138,106,22,.14)]" : "border-black/10"}`}><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">{title}</h3>{featured ? <span className="rounded-full bg-[#f3e5b5] px-3 py-1 text-[11px] font-semibold text-[#6d5310]">Best value</span> : null}</div><p className="mt-6 text-4xl font-semibold tracking-[-.04em]">{price}</p><p className="mt-1 text-sm text-[#777]">{note}</p><p className="mt-6 min-h-18 leading-7 text-[#5f5f5f]">{copy}</p><ul className="mt-6 flex-1 space-y-3 border-t border-black/8 pt-6 text-sm">{features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-[#8a6a16]">✓</span>{feature}</li>)}</ul><a href={href} className={`mt-7 inline-flex min-h-12 items-center justify-center rounded-lg px-5 text-center text-sm font-semibold ${featured ? "bg-[#8a6a16] text-white" : "border border-black/15 text-[#101010]"}`}>{cta}</a>{secondary ? <a href={secondary.href} className="mt-3 text-center text-sm text-[#6d5310] underline underline-offset-4">{secondary.label}</a> : null}</article>;
}
