"use client";

import { useMemo, useState } from "react";

const registerUrl = "https://app.aifrogi.com/register?source=pricing";
const connectors = [
  { id: "sheets", name: "Google Sheets", use: "Approved leads, enquiries and operational records.", india: 2999, global: 59, from: false },
  { id: "calendar", name: "Google Calendar", use: "Availability, appointments and reminders.", india: 2999, global: 59, from: false },
  { id: "commerce", name: "E-commerce Store", use: "Shopify, WooCommerce or supported store API.", india: 14999, global: 299, from: true },
  { id: "pms", name: "PMS / Channel Manager", use: "Hotel availability and reservation workflows.", india: 24999, global: 499, from: true }
] as const;

export function AiBotPricing() {
  const [annual, setAnnual] = useState(false);
  const [region, setRegion] = useState<"india" | "global">("india");
  const [selected, setSelected] = useState<string[]>(["sheets", "calendar"]);
  const total = useMemo(() => connectors.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + item[region], 0), [region, selected]);
  const money = (value: number) => region === "india" ? `₹${value.toLocaleString("en-IN")}` : `$${value.toLocaleString("en-US")}`;
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);

  return <>
    <section className="bg-[#050505] px-5 py-20 text-center text-white sm:px-8 sm:py-24">
      <div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#e2c66d]">AI Bot pricing</p><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-6xl">Start small. Prove value. Scale with control.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/65">One governed AI Business Bot, approved knowledge, human handover and measurable conversations. Connector and provider costs remain transparent.</p></div>
    </section>

    <section id="plans" className="bg-[#fbfaf7] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl">
      <div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="product-eyebrow">Simple foundation</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Choose how you begin.</h2><p className="mt-4 leading-7 text-[var(--text-muted)]">Starter is an introductory launch offer for one AI Bot. Included allowances are published below; third-party charges remain separate.</p></div><div className="inline-flex w-fit rounded-full border border-black/10 bg-white p-1"><button type="button" onClick={() => setAnnual(false)} className={`rounded-full px-5 py-2 text-sm ${!annual ? "bg-[#8a6a16] font-semibold text-white" : "text-[#404040]"}`}>Monthly</button><button type="button" onClick={() => setAnnual(true)} className={`rounded-full px-5 py-2 text-sm ${annual ? "bg-[#8a6a16] font-semibold text-white" : "text-[#404040]"}`}>Yearly · save ₹989</button></div></div>
      <div className="mt-10 grid gap-5 lg:grid-cols-3">
        <Plan title="15-day trial" price="₹0" note="No card required" copy="Validate the bot on your approved knowledge before subscribing." features={["One demo AI Bot", "Website widget and shareable link", "Approved knowledge setup", "Human-contact handover", "Pauses after day 15"]} cta="Start free trial" href={registerUrl} />
        <Plan featured title="Starter" price={annual ? "₹4,999" : "₹499"} note={annual ? "per year · billed annually" : "per month · billed monthly"} copy="For a small business operating one focused customer journey." features={["One live AI Business Bot", "Widget and standalone link", "Up to 3 team users", "Knowledge and persona updates", "Conversation evidence and feedback", "Published usage allowances", "Email support"]} cta="Choose Starter" href={`${registerUrl}&plan=starter&billing=${annual ? "yearly" : "monthly"}`} />
        <Plan title="Custom / Enterprise" price="Let’s talk" note="Scope-based proposal" copy="For multiple bots, locations, complex connectors, governance or higher usage." features={["Multi-bot or multi-location", "Custom workflows and connectors", "Advanced roles and reporting", "Security and rollout planning", "Priority support options"]} cta="Email info@aifrogi.com" href="mailto:info@aifrogi.com?subject=AiFrogi%20Enterprise%20Plan" secondary={{ label: "WhatsApp +91-7410582898", href: "https://wa.me/917410582898?text=I%20would%20like%20to%20discuss%20an%20AiFrogi%20plan." }} />
      </div>
      <div id="plan-limits" className="mt-8 grid gap-4 rounded-2xl border border-black/10 bg-white p-6 md:grid-cols-[.7fr_1fr_1fr]"><div><p className="product-eyebrow">Published allowances</p><h3 className="mt-2 text-xl font-semibold">No surprise cap.</h3><p className="mt-2 text-sm leading-6 text-[#666]">Usage is visible in the customer dashboard. AiFrogi does not apply an automatic overage charge without prior agreement.</p></div><Allowance title="15-day trial" values={["100 AI replies", "500 total messages", "250 saved contacts", "1 campaign", "Up to 2 team users"]} /><Allowance title="Starter launch allowance" values={["1,000 AI replies", "5,000 total messages", "2,000 saved contacts", "5 campaigns", "Up to 3 team users"]} /></div>
    </div></section>

    <WhatsAppPricing />

    <section className="bg-white px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl">
      <div className="max-w-3xl"><p className="product-eyebrow">Optional connectors</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Connect actions only when needed.</h2><p className="mt-4 leading-7 text-[var(--text-muted)]">Indicative one-time implementation charges—not Google or software-provider fees. Final scope depends on API access, data quality and workflow complexity.</p></div>
      <div className="mt-10 overflow-x-auto rounded-2xl border border-black/10"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#101010] text-white"><tr><th className="p-5">Connector</th><th className="p-5">Typical use</th><th className="p-5">India setup</th><th className="p-5">Global setup</th></tr></thead><tbody>{connectors.map((item) => <tr key={item.id} className="border-t border-black/8"><th className="p-5 font-semibold">{item.name}</th><td className="p-5 text-[#5f5f5f]">{item.use}</td><td className="p-5">{item.from ? "From " : ""}₹{item.india.toLocaleString("en-IN")}</td><td className="p-5">{item.from ? "From " : ""}${item.global}</td></tr>)}</tbody></table></div>
      <div className="mt-8 grid overflow-hidden rounded-2xl bg-[#050505] text-white lg:grid-cols-[.8fr_1.2fr]"><div className="p-7 sm:p-9"><p className="text-xs uppercase tracking-[.18em] text-[#e2c66d]">Connector estimator</p><h3 className="mt-3 text-2xl font-semibold">Estimate initial setup.</h3><p className="mt-3 text-sm leading-6 text-white/60">Planning estimate only. Credentials, subscriptions, taxes and custom development are excluded.</p><div className="mt-6 inline-flex rounded-full border border-white/15 p-1"><button type="button" onClick={() => setRegion("india")} className={`rounded-full px-4 py-2 text-sm ${region === "india" ? "bg-[#8a6a16]" : "text-white/65"}`}>India</button><button type="button" onClick={() => setRegion("global")} className={`rounded-full px-4 py-2 text-sm ${region === "global" ? "bg-[#8a6a16]" : "text-white/65"}`}>Global</button></div></div><div className="border-t border-white/10 p-7 sm:p-9 lg:border-l lg:border-t-0"><div className="grid gap-3 sm:grid-cols-2">{connectors.map((item) => <label key={item.id} className={`flex cursor-pointer items-center justify-between gap-4 rounded-xl border p-4 ${selected.includes(item.id) ? "border-[#b28728] bg-[#8a6a16]/15" : "border-white/12 bg-white/[.03]"}`}><span><strong className="block text-sm">{item.name}</strong><small className="text-white/50">{item.from ? "From " : ""}{money(item[region])}</small></span><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} className="size-4 accent-[#b28728]" /></label>)}</div><div className="mt-6 flex items-end justify-between gap-6 border-t border-white/12 pt-6"><span className="text-sm text-white/55">Indicative one-time total</span><strong className="text-right text-3xl text-[#e2c66d]">{selected.some((id) => id === "commerce" || id === "pms") ? "From " : ""}{money(total)}</strong></div></div></div>
      <div className="mt-6 grid gap-4 text-sm leading-6 text-[#5f5f5f] md:grid-cols-3"><p><strong className="block text-[#101010]">Optional monitoring</strong>From ₹1,499/month or $29/month for connector health and incident review.</p><p><strong className="block text-[#101010]">Provider usage</strong>OpenAI, PMS, commerce, Meta or other provider charges are separate where applicable.</p><p><strong className="block text-[#101010]">Google Workspace APIs</strong>Google currently publishes quota-based usage; provider terms and pricing can change.</p></div>
    </div></section>

    <section className="bg-[#f3e5b5] px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs uppercase tracking-[.18em] text-[#6d5310]">Before payment</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em]">Clear commercial terms.</h2></div><div className="grid gap-5 text-sm leading-6 text-[#404040] sm:grid-cols-2"><p><strong className="block text-[#101010]">Subscriptions</strong>Paid in advance and renew until cancelled. Cancellation stops the next renewal; access continues to the paid-period end.</p><p><strong className="block text-[#101010]">Connector projects</strong>Scope, milestones, dependencies and provider access are confirmed before work begins.</p><p><strong className="block text-[#101010]">Refunds</strong>Duplicate or erroneous payments are reviewed. Activated subscriptions and completed work are generally non-refundable, subject to applicable law.</p><p><strong className="block text-[#101010]">Allowances and extras</strong>Current limits are published above. Taxes, higher usage, provider fees and custom work are disclosed before billing whenever applicable.</p></div><div className="lg:col-start-2"><a href="/terms-of-service" className="inline-flex rounded-lg bg-[#8a6a16] px-5 py-3 text-sm font-semibold text-white">Read full payment and service terms</a></div></div></section>
  </>;
}

export function WhatsAppPricing() {
  const standard = ["One WhatsApp number", "One connector: calendar, payment or CRM", "Answer, Clarify and Recommend authority", "Template and delivery monitoring", "Signed webhook security", "Human takeover", "Meta usage billed separately"];
  const premium = ["Calendar, CRM and payment together", "Full Act and Verify authority", "Live booking and payment actions", "Priority template review", "Dedicated monitoring", "Multi-number and multi-location ready", "Human takeover", "Meta usage billed separately"];
  return <section id="whatsapp-channel" className="bg-[#050505] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl">
    <div className="max-w-3xl"><p className="text-xs uppercase tracking-[.18em] text-[#e2c66d]">Optional channel</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] sm:text-5xl">Add WhatsApp to your AI Bot.</h2><p className="mt-5 text-base leading-7 text-white/60">WhatsApp is an optional channel. Meta usage and third-party charges apply separately.</p></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-2">
      <ChannelPlan title="Standard" price="₹1,250" note="per month · billed quarterly (₹3,750/qtr)" copy="For a Business or Intelligent Bot using one connector on WhatsApp." features={standard} cta="Add WhatsApp" href={`${registerUrl}&channel=whatsapp&tier=standard`} />
      <ChannelPlan featured title="Premium" price="₹8,500" note="per month · billed quarterly (₹25,500/qtr)" copy="For Agentic and Custom Enterprise bots that book, pay and act on WhatsApp." features={premium} cta="Talk to us about Premium" href="https://wa.me/917410582898?text=I%20would%20like%20to%20discuss%20AiFrogi%20WhatsApp%20Premium." />
    </div>
    <div className="mt-5 rounded-2xl border border-[#b28728]/45 bg-[#8a6a16]/16 px-6 py-5 sm:flex sm:items-center sm:justify-between sm:gap-8"><div><h3 className="text-lg font-semibold text-[#e2c66d]">One-time setup — ₹4,500</h3><p className="mt-1 text-sm leading-6 text-white/62">Meta, Razorpay and Google onboarding with one test transaction. Charged once, regardless of tier.</p></div><span className="mt-3 inline-flex rounded-full bg-[#e2c66d] px-3 py-1 text-xs font-semibold text-[#404040] sm:mt-0">One-time</span></div>
    <div className="mt-8 overflow-hidden rounded-2xl border border-white/12 bg-white/[.04]"><div className="border-b border-white/10 px-6 py-5"><h3 className="text-xl font-semibold">Connector setup, by complexity</h3><p className="mt-2 text-sm text-white/52">These ranges cover limited WhatsApp-channel adapter setup. Broader end-to-end integrations are scoped separately below.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-[#e2c66d]"><tr><th className="px-6 py-4">Complexity</th><th className="px-6 py-4">Examples</th><th className="px-6 py-4">One-time fee</th></tr></thead><tbody className="text-white/70"><tr className="border-t border-white/10"><th className="px-6 py-4 text-white">Simple</th><td className="px-6 py-4">Google Sheets, Google Calendar</td><td className="px-6 py-4">₹1,500–2,500</td></tr><tr className="border-t border-white/10"><th className="px-6 py-4 text-white">Complex</th><td className="px-6 py-4">CRM, Shopify/WooCommerce</td><td className="px-6 py-4">₹5,000–8,000</td></tr><tr className="border-t border-white/10"><th className="px-6 py-4 text-white">High</th><td className="px-6 py-4">PMS, channel manager, custom API</td><td className="px-6 py-4">₹8,000–15,000</td></tr></tbody></table></div><p className="border-t border-white/10 px-6 py-4 text-xs leading-5 text-white/48">Standard connectors such as Razorpay and WhatsApp Flow are included in the ₹4,500 setup when they fit the agreed standard onboarding scope.</p></div>
    <p className="mt-6 text-sm text-white/55">Meta charges by delivered message, category and country—always shown separately. <a href="/whatsapp-api#calculator" className="font-semibold text-[#e2c66d] underline underline-offset-4">View Meta cost calculator →</a></p>
  </div></section>;
}

function ChannelPlan({ title, price, note, copy, features, cta, href, featured = false }: { title: string; price: string; note: string; copy: string; features: string[]; cta: string; href: string; featured?: boolean }) {
  return <article className={`flex flex-col rounded-2xl border p-7 ${featured ? "border-[#b28728] bg-[#12100a] shadow-[0_20px_60px_rgba(178,135,40,.16)]" : "border-white/14 bg-white/[.04]"}`}><div className="flex items-center justify-between gap-4"><h3 className="text-2xl font-semibold">{title}</h3>{featured ? <span className="rounded-full bg-[#e2c66d] px-3 py-1 text-[11px] font-semibold text-[#404040]">Best for scale</span> : null}</div><p className="mt-6 text-4xl font-semibold tracking-[-.04em]">{price}</p><p className="mt-1 text-sm text-white/52">{note}</p><p className="mt-6 min-h-14 leading-7 text-white/65">{copy}</p><ul className="mt-6 flex-1 space-y-3 border-t border-white/10 pt-6 text-sm text-white/78">{features.map((feature) => <li key={feature} className="flex gap-2.5"><span className="text-[#e2c66d]">✓</span><span>{feature}</span></li>)}</ul><a href={href} className={`mt-7 inline-flex min-h-12 items-center justify-center rounded-lg px-5 text-center text-sm font-semibold ${featured ? "bg-[#8a6a16] text-white" : "border border-[#b28728] text-[#e2c66d]"}`}>{cta}</a></article>;
}

function Allowance({ title, values }: { title: string; values: string[] }) {
  return <div className="rounded-xl bg-[#fbfaf7] p-5"><h4 className="font-semibold">{title}</h4><ul className="mt-3 grid gap-2 text-sm text-[#5f5f5f] sm:grid-cols-2 md:grid-cols-1">{values.map((value) => <li key={value} className="flex gap-2"><span className="text-[#8a6a16]">•</span>{value}</li>)}</ul></div>;
}

function Plan({ title, price, note, copy, features, cta, href, featured = false, secondary }: { title: string; price: string; note: string; copy: string; features: string[]; cta: string; href: string; featured?: boolean; secondary?: { label: string; href: string } }) {
  return <article className={`flex flex-col rounded-2xl border bg-white p-7 ${featured ? "border-[#8a6a16] shadow-[0_20px_60px_rgba(138,106,22,.14)]" : "border-black/10"}`}><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">{title}</h3>{featured ? <span className="rounded-full bg-[#f3e5b5] px-3 py-1 text-[11px] font-semibold text-[#6d5310]">Best value</span> : null}</div><p className="mt-6 text-4xl font-semibold tracking-[-.04em]">{price}</p><p className="mt-1 text-sm text-[#777]">{note}</p><p className="mt-6 min-h-18 leading-7 text-[#5f5f5f]">{copy}</p><ul className="mt-6 flex-1 space-y-3 border-t border-black/8 pt-6 text-sm">{features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-[#8a6a16]">✓</span>{feature}</li>)}</ul><a href={href} className={`mt-7 inline-flex min-h-12 items-center justify-center rounded-lg px-5 text-center text-sm font-semibold ${featured ? "bg-[#8a6a16] text-white" : "border border-black/15 text-[#101010]"}`}>{cta}</a>{secondary ? <a href={secondary.href} className="mt-3 text-center text-sm text-[#6d5310] underline underline-offset-4">{secondary.label}</a> : null}</article>;
}
