function escape(value: string) {
  return value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

export type BillingEmailEvent = "PLAN_ACTIVATED" | "CREDITS_PURCHASED" | "FREE_CREDITS_GRANTED";

export function billingEmail(input: { event: BillingEmailEvent; ownerName: string; businessName: string; description: string; value: string; reference?: string | null; validity?: Date | null }) {
  const heading = input.event === "PLAN_ACTIVATED" ? "Your AiFrogi plan is active." : input.event === "CREDITS_PURCHASED" ? "Your AI reply credits are ready." : "Free AI reply credits were added.";
  const label = input.event === "PLAN_ACTIVATED" ? "PLAN ACTIVATED" : input.event === "CREDITS_PURCHASED" ? "CREDITS PURCHASED" : "FREE CREDITS GRANTED";
  const validity = input.validity ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(input.validity) : null;
  const details = [input.description, input.value, input.reference ? `Reference: ${input.reference}` : null, validity ? `Valid until: ${validity}` : null].filter(Boolean).join("\n");
  const body = `Hello ${input.ownerName},\n\n${heading}\n\nBusiness: ${input.businessName}\n${details}\n\nReview billing and usage: https://app.aifrogi.com/billing\n\nSupport: info@aifrogi.com | +91-7410582898`;
  const html = `<!doctype html><html><body style="margin:0;background:#f4f1e8;font-family:Arial,sans-serif;color:#101010"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:650px;background:#fff;border:1px solid #ded8cb;border-radius:18px;overflow:hidden"><tr><td style="padding:28px 30px;background:#050505"><img src="https://app.aifrogi.com/brand/aifrogi-logo-white.png" width="170" alt="AiFrogi" style="display:block;width:170px;max-width:100%;height:auto"><p style="margin:20px 0 0;color:#e2c66d;font-size:11px;letter-spacing:2px">${label}</p></td></tr><tr><td style="padding:30px"><h1 style="margin:0 0 18px;font-size:28px;line-height:1.3">${escape(heading)}</h1><p style="color:#5f5b54;line-height:1.7">Hello ${escape(input.ownerName)},</p><p style="color:#5f5b54;line-height:1.7">This billing update has been applied immediately to <strong>${escape(input.businessName)}</strong>.</p><div style="margin:22px 0;padding:18px;background:#f7f4ed;border-left:4px solid #8a6a16"><strong>${escape(input.description)}</strong><p style="margin:8px 0 0;color:#5f5b54">${escape(input.value)}</p>${input.reference ? `<p style="margin:8px 0 0;color:#5f5b54">Reference: ${escape(input.reference)}</p>` : ""}${validity ? `<p style="margin:8px 0 0;color:#5f5b54">Valid until: ${escape(validity)}</p>` : ""}</div><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="background:#8a6a16;border-radius:7px"><a href="https://app.aifrogi.com/billing" style="display:inline-block;padding:15px 22px;color:#fff;text-decoration:none;font-weight:bold">Review billing and usage</a></td></tr></table><p style="margin-top:24px;font-size:12px;line-height:1.6;color:#756f64">AiFrogi never asks for card, bank, UPI, password or OTP details by email.</p></td></tr><tr><td style="padding:22px 30px;background:#404040;color:#e3e3e3;font-size:12px;line-height:1.8"><strong style="color:#fff">AiFrogi</strong><br><a href="tel:+917410582898" style="color:#e2c66d;text-decoration:none">+91-7410582898</a> &nbsp;·&nbsp; <a href="mailto:info@aifrogi.com" style="color:#e2c66d;text-decoration:none">info@aifrogi.com</a><br>AI Business Automation by Webtechnosys</td></tr></table></td></tr></table></body></html>`;
  return { subject: heading, body, html };
}
