function escape(value: string) {
  return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

/** Matches the approved installation-kit branding; no credentials in email. */
export function botLiveEmail(input: { ownerName: string; businessName: string; slug: string }) {
  const botUrl = `https://app.aifrogi.com/bot/${encodeURIComponent(input.slug)}`;
  const body = `Hello ${input.ownerName},\n\n${input.businessName}'s AI Bot has been approved by AiFrogi and is now live.\n\nOpen My AI Bot: ${botUrl}\nManage knowledge: https://app.aifrogi.com/knowledge\nReview feedback: https://app.aifrogi.com/improve\n\nSupport: info@aifrogi.com | +91-7410582898`;
  const html = `<!doctype html><html><body style="margin:0;background:#f4f1e8;font-family:Arial,sans-serif;color:#101010"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:650px;background:#fff;border:1px solid #ded8cb;border-radius:18px;overflow:hidden"><tr><td style="padding:28px 30px;background:#050505"><img src="https://app.aifrogi.com/brand/aifrogi-logo-white.png" width="170" alt="AiFrogi" style="display:block;width:170px;max-width:100%;height:auto"><p style="margin:20px 0 0;color:#e2c66d;font-size:11px;letter-spacing:2px">YOUR AI BOT IS LIVE</p></td></tr><tr><td style="padding:30px"><h1 style="margin:0 0 18px;font-size:28px;line-height:1.3">Ready to welcome your customers.</h1><p style="color:#5f5b54;line-height:1.7">Hello ${escape(input.ownerName)},</p><p style="color:#5f5b54;line-height:1.7"><strong>${escape(input.businessName)}</strong>'s AI Bot has been approved and activated. Customers can now access your bot.</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="background:#8a6a16;border-radius:7px"><a href="${escape(botUrl)}" style="display:inline-block;padding:15px 22px;color:#fff;text-decoration:none;font-weight:bold">Open My AI Bot</a></td></tr></table><p style="margin-top:28px;color:#5f5b54;line-height:1.7">Keep your information current in <a href="https://app.aifrogi.com/knowledge" style="color:#6d5310">Intelligence</a> and review customer feedback in <a href="https://app.aifrogi.com/improve" style="color:#6d5310">Improve My Bot</a>.</p><p style="font-size:12px;line-height:1.6;color:#756f64">If the button does not open, use:<br><a href="${escape(botUrl)}" style="color:#6d5310;word-break:break-all">${escape(botUrl)}</a></p></td></tr><tr><td style="padding:22px 30px;background:#404040;color:#e3e3e3;font-size:12px;line-height:1.8"><strong style="color:#fff">AiFrogi</strong><br><a href="tel:+917410582898" style="color:#e2c66d;text-decoration:none">+91-7410582898</a> &nbsp;·&nbsp; <a href="mailto:info@aifrogi.com" style="color:#e2c66d;text-decoration:none">info@aifrogi.com</a><br>AI Business Automation by Webtechnosys</td></tr></table></td></tr></table></body></html>`;
  return { body, html };
}
