import Link from "next/link";
import { getDb } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function WhatsAppAiBotOperationsPage() {
  const db = getDb();
  const organizations = db ? await db.organization.findMany({ where: { isDemo: false, botProfile: { channels: { has: "WHATSAPP" } } }, include: { botProfile: true, onboarding: true, botConfiguration: true }, orderBy: { updatedAt: "desc" } }) : [];
  const connected = organizations.filter((item) => ["CONNECTED", "LIVE"].includes(item.onboarding?.metaStatus || "")).length;
  const live = organizations.filter((item) => item.onboarding?.metaStatus === "LIVE" || item.botConfiguration?.enabled).length;
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-7 sm:px-8"><section className="overflow-hidden rounded-[30px] bg-[#080808] p-7 text-white sm:p-10"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#e2c66d]">Separate delivery track</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">WhatsApp AI Bot</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">Operate Meta connection, phone verification, templates, webhooks and WhatsApp go-live without mixing them into website AI Bot onboarding.</p><div className="mt-8 flex flex-wrap gap-3"><Metric label="Enabled" value={organizations.length} /><Metric label="Meta connected" value={connected} /><Metric label="Live" value={live} /></div></section><section className="overflow-hidden rounded-[26px] border border-black/7 bg-white"><div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">WhatsApp clients</p><h2 className="mt-2 text-2xl font-semibold">Connection and launch queue</h2></div><div className="divide-y divide-black/6">{organizations.map((organization) => <div key={organization.id} className="grid gap-4 px-6 py-5 md:grid-cols-[1fr_auto_auto] md:items-center"><div><strong>{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.botProfile?.personaName || "AI Bot"} · {organization.ownerEmail}</small></div><span className={`status-pill ${organization.onboarding?.metaStatus === "LIVE" ? "status-success" : "status-warning"}`}>{organization.onboarding?.metaStatus?.replaceAll("_", " ").toLowerCase() || "not started"}</span><Link href={`/admin/customers/${organization.id}?onboarding=whatsapp`} className="inline-flex min-h-10 items-center justify-center rounded-full bg-[#101010] px-4 text-xs font-bold text-white">Open WhatsApp setup</Link></div>)}{!organizations.length ? <div className="px-6 py-12 text-center"><h3 className="font-semibold">No WhatsApp AI Bot enabled</h3><p className="mt-2 text-sm text-[#68645c]">Enable WhatsApp deliberately from a client’s separate onboarding track.</p><Link href="/admin/customers" className="mt-4 inline-flex text-sm font-bold text-[#8a6a16]">Open customers →</Link></div> : null}</div></section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-full border border-white/12 bg-white/6 px-5 py-3"><span className="text-xs text-white/45">{label}</span><strong className="ml-3 text-lg">{value}</strong></div>; }
