import Link from "next/link";
import { getDb } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function WhatsAppAiBotOperationsPage() {
  const db = getDb();
  const organizations = db ? await db.organization.findMany({ where: { isDemo: false, status: { not: "REMOVED" } }, include: { botProfile: true, onboarding: true, botConfiguration: true }, orderBy: { updatedAt: "desc" } }) : [];
  const enabled = organizations.filter((item) => item.botProfile?.channels.includes("WHATSAPP"));
  const connected = enabled.filter((item) => item.onboarding?.facebookStatus === "CONNECTED").length;
  const live = enabled.filter((item) => item.onboarding?.metaStatus === "LIVE" && item.botConfiguration?.enabled).length;
  const blocked = enabled.filter((item) => item.onboarding?.metaStatus === "REJECTED" || item.onboarding?.lastError).length;
  return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-black/8 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="product-eyebrow">Independent product operation</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">WhatsApp AI Bot</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#68645c]">Enable the channel deliberately, collect Meta authorisation, provision the WhatsApp API, secure the webhook and release only after a verified message test.</p></div><Link href="/admin/customers" className="rounded-full bg-[#101010] px-6 py-3 text-sm font-bold text-white">Choose a customer</Link></header>
    <section className="grid overflow-hidden border border-white/70 bg-white sm:grid-cols-2 xl:grid-cols-4">{[["Enabled",enabled.length],["Meta connected",connected],["WhatsApp live",live],["Blocked",blocked]].map(([label,value],index) => <div key={label} className={`p-6 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#777168]">{label}</p><strong className={`mt-3 block text-3xl ${label === "Blocked" && Number(value) ? "text-[#b53b33]" : ""}`}>{value}</strong></div>)}</section>
    <section className="overflow-hidden border border-white/70 bg-[#0a0a0a] p-7 text-white sm:p-9"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#d9ba58]">Automated integration rail</p><div className="mt-6 grid gap-6 md:grid-cols-4">{[["01","Enable WhatsApp","Add the channel to the approved bot profile"],["02","Authorise Meta","Business owner completes secure Meta connection"],["03","Provision API","Number, credential and signed webhook are configured"],["04","Verify and release","Template plus inbound/outbound test must pass"]].map(([number,title,copy]) => <div key={number} className="border-l border-white/15 pl-4"><span className="text-xs font-bold text-[#d9ba58]">{number}</span><strong className="mt-2 block">{title}</strong><p className="mt-2 text-xs leading-5 text-white/48">{copy}</p></div>)}</div><p className="mt-7 text-xs leading-5 text-white/42">Meta authorisation cannot be performed silently by AiFrogi. The system automates provisioning and verification after the business owner grants approved access.</p></section>
    <section className="overflow-hidden border border-white/70 bg-white"><div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">Integration queue</p><h2 className="mt-2 text-2xl font-semibold">Every customer and its next WhatsApp action</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-[#f5f2eb] text-[10px] uppercase tracking-[.13em] text-[#68645c]"><tr><th className="px-6 py-4">Customer</th><th className="px-6 py-4">Channel</th><th className="px-6 py-4">Meta</th><th className="px-6 py-4">API / webhook</th><th className="px-6 py-4">Release</th><th className="px-6 py-4">Action</th></tr></thead><tbody className="divide-y divide-black/5">{organizations.map((organization) => { const has = organization.botProfile?.channels.includes("WHATSAPP") || false; const status = organization.onboarding?.metaStatus || "NOT_STARTED"; return <tr key={organization.id}><td className="px-6 py-5"><strong>{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.botProfile?.personaName || "AI Bot not configured"}</small></td><td className="px-6 py-5"><State ok={has} label={has ? "Enabled" : "Not enabled"} /></td><td className="px-6 py-5"><State ok={organization.onboarding?.facebookStatus === "CONNECTED"} label={organization.onboarding?.facebookStatus || "Not started"} /></td><td className="px-6 py-5"><strong className="block text-xs">{organization.onboarding?.tokenStatus || "No credential"}</strong><small className="mt-1 block text-[#68645c]">Webhook · {organization.onboarding?.webhookStatus || "Not configured"}</small></td><td className="px-6 py-5"><State ok={status === "LIVE" && Boolean(organization.botConfiguration?.enabled)} label={status === "LIVE" ? organization.botConfiguration?.enabled ? "Live" : "Ready to enable" : status} /></td><td className="px-6 py-5"><Link href={`/admin/customers/${organization.id}?onboarding=${has ? "whatsapp" : "ai-bot"}`} className="rounded-full bg-[#101010] px-4 py-2 text-xs font-bold text-white">{has ? "Continue setup" : "Enable in bot profile"}</Link></td></tr>; })}{!organizations.length ? <tr><td colSpan={6} className="px-6 py-12 text-center text-[#68645c]">No active customer exists.</td></tr> : null}</tbody></table></div></section>
  </main>;
}

function State({ ok, label }: { ok: boolean; label: string }) { return <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold ${ok ? "bg-[#eaf7f1] text-[#17694f]" : "bg-[#f4f0e7] text-[#6b6254]"}`}><span className={`h-2 w-2 rounded-full ${ok ? "bg-[#36a77a]" : "bg-[#c79b23]"}`} />{label.replaceAll("_"," ")}</span>; }
