import { getSovereignIntelligenceReport } from "@/lib/repositories/sovereign-evidence-repository";
import { SOVEREIGN_CONSTITUTION } from "@/lib/sovereign-intelligence/constitution";
import { listVersionedBotBlueprints } from "@/lib/sovereign-intelligence/registry";
import { runSovereignCommonEvaluation, scoreSovereignEvaluation } from "@/lib/sovereign-intelligence/evaluation";
import { gradeReliabilitySection } from "@/lib/reliability/grading";
import { getAllBotImprovementReport } from "@/lib/repositories/improvement-report-repository";

export const dynamic = "force-dynamic";

export default async function SovereignIntelligencePage() {
  const [report, botOperations] = await Promise.all([getSovereignIntelligenceReport(), getAllBotImprovementReport()]);
  const blueprints = listVersionedBotBlueprints();
  const evaluation = scoreSovereignEvaluation(runSovereignCommonEvaluation());
  const groundedRate = report.total ? Math.round((report.grounded / report.total) * 100) : 0;
  const reliabilityGrade = gradeReliabilitySection({ "R7-02": true, "R7-03": true, "R7-04": true, "R7-05": report.total > 0 });
  const trialGrade = evaluation.releasePassed && report.total > 0 && reliabilityGrade.complete;
  const checks = [
    ["Constitution", `Rule ${SOVEREIGN_CONSTITUTION.version} locked`, true],
    ["Category registry", `${blueprints.length} versioned blueprints`, blueprints.length > 0],
    ["Common evaluation", evaluation.suiteComplete ? `${evaluation.srr}% SRR · ${evaluation.total}/${evaluation.required} cases · threshold ${evaluation.threshold}%` : `Score withheld · ${evaluation.total}/${evaluation.required} cases · ${evaluation.missingIds.length} missing`, evaluation.releasePassed],
    ["Zero-tolerance gates", evaluation.gates.map((gate)=>`${gate.gate.replaceAll("_"," ")} ${gate.rate}%`).join(" · "), evaluation.zeroTolerancePassed],
    ["Evidence ledger", `${report.total} production decisions retained`, report.total > 0],
    ["Bounded resolution", `${report.circuitBreakers} loops stopped · ${report.unresolved} unresolved`, true],
    ["Reliability Section 7", `${reliabilityGrade.results.filter((item)=>item.passed).length}/${reliabilityGrade.results.length} evidence controls · ${reliabilityGrade.certification.toLowerCase()}`, reliabilityGrade.complete]
  ] as const;

  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-7 sm:px-8">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="product-eyebrow">All bots · all clients</p><h1 className="mt-2 text-3xl font-semibold">Intelligence Operations</h1><p className="mt-2 max-w-3xl text-sm text-[var(--text-muted)]">Cross-tenant operational visibility without allowing one client’s business correction to alter another client’s knowledge.</p></div><span className={`status-pill ${trialGrade?"status-success":"status-warning"}`}>{trialGrade?"Trial-Grade ready":"Evidence required"}</span></section>
    <section className="overflow-hidden rounded-[26px] border border-black/7 bg-white shadow-sm"><div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">Bot improvement estate</p><h2 className="mt-2 text-xl font-semibold">Client and persona attention queue</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Prioritize incorrect facts and pending regressions before ordinary knowledge gaps.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#f7f6f2] text-xs text-[var(--text-muted)]"><tr><th className="px-5 py-3">Client bot</th><th className="px-5 py-3">SRR</th><th className="px-5 py-3">Helpful</th><th className="px-5 py-3">Negative</th><th className="px-5 py-3">Incorrect facts</th><th className="px-5 py-3">Knowledge gaps</th><th className="px-5 py-3">Regression review</th></tr></thead><tbody className="divide-y divide-black/6">{botOperations.map((bot)=><tr key={bot.id}><td className="px-5 py-4"><strong className="block">{bot.name}</strong><small className="text-[var(--text-muted)]">{bot.organization?.name || bot.slug}</small></td><td className="px-5 py-4">{bot.safeResolutionRate === null ? "—" : `${bot.safeResolutionRate}%`}</td><td className="px-5 py-4">{bot.helpfulRate === null ? "—" : `${bot.helpfulRate}%`}</td><td className="px-5 py-4">{bot.negative}</td><td className={`px-5 py-4 font-bold ${bot.openFlags ? "text-[#b23a32]" : "text-[var(--success)]"}`}>{bot.openFlags}</td><td className="px-5 py-4">{bot.openGaps}</td><td className={`px-5 py-4 font-bold ${bot.pendingReplay ? "text-[#8a6a16]" : "text-[var(--success)]"}`}>{bot.pendingReplay}</td></tr>)}</tbody></table></div>{botOperations.length ? null : <p className="px-6 py-10 text-center text-sm text-[var(--text-muted)]">Client bot reporting begins after the first workspace produces evidence.</p>}</section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Metric label="SRR evaluation" value={evaluation.srr === null ? "Withheld" : `${evaluation.srr}%`} helper={`${evaluation.total}/${evaluation.required} required cases`}/><Metric label="Evidence integrity" value={report.consistencyRate === null ? "No sample" : `${report.consistencyRate}%`} helper={`${report.consistencyMismatches} decision mismatch${report.consistencyMismatches === 1 ? "" : "es"}`}/><Metric label="Decisions" value={report.total} helper="Evidence records"/><Metric label="Grounded" value={`${groundedRate}%`} helper={`${report.grounded} source-backed`}/><Metric label="Visitor helpful" value={report.helpfulRate === null ? "No sample" : `${report.helpfulRate}%`} helper={`${report.feedbackTotal} rated answers`}/><Metric label="Near misses" value={report.nearMisses} helper="Relevant claims not selected"/><Metric label="Replay cases" value={report.replayCases} helper={`${report.pendingReplayCases} pending review`}/><Metric label="Automated resolution" value={report.automatedResolutionRate === null ? "No sample" : `${report.automatedResolutionRate}%`} helper={`${report.tier0} Tier 0 conversations`}/><Metric label="Support calls / 1,000" value={report.supportCallsPerThousand === null ? "No sample" : report.supportCallsPerThousand} helper={`${report.tier3} Tier 3 records`}/><Metric label="Model latency" value={`${report.averageLatencyMs} ms`} helper="Measured governed turns"/><Metric label="Reliability failures" value={report.failures} helper={`${report.degraded} degraded turns`}/><Metric label="Business async" value={report.tier1} helper="Tier 1 handovers"/><Metric label="AiFrogi async" value={report.tier2} helper="Tier 2 defects"/><Metric label="Loops stopped" value={report.circuitBreakers} helper="Circuit breakers"/><Metric label="Fallback" value={report.fallback} helper="Needs review"/></section>
    <section className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-lg border border-black/7 bg-white p-6 shadow-sm"><p className="product-eyebrow">Readiness gates</p><h2 className="mt-2 text-xl font-semibold">Measured shared runtime</h2><div className="mt-5 divide-y divide-black/8 border-y border-black/8">{checks.map(([label,detail,complete])=><div key={label} className="flex items-center justify-between gap-4 py-4"><div><strong className="text-sm">{label}</strong><p className="mt-1 max-w-xl text-xs text-[var(--text-muted)]">{detail}</p></div><span className={`status-pill ${complete?"status-success":"status-warning"}`}>{complete?"ready":"pending"}</span></div>)}</div></div><div className="rounded-lg border border-black/7 bg-[#101010] p-6 text-white shadow-sm"><p className="product-eyebrow text-[#e2c66d]">Constitution {SOVEREIGN_CONSTITUTION.version}</p><h2 className="mt-2 text-xl font-semibold">Eleven rules govern every category.</h2><ol className="mt-5 grid gap-2 text-sm text-white/70">{SOVEREIGN_CONSTITUTION.rules.map((rule,index)=><li key={rule.code}><span className="mr-2 font-mono text-[#e2c66d]">{String(index+1).padStart(2,"0")}</span>{rule.code.replaceAll("_"," ")}</li>)}</ol></div></section>
    <section className="rounded-lg border border-black/7 bg-white p-6 shadow-sm"><p className="product-eyebrow">Persona-level intelligence</p><h2 className="mt-2 text-xl font-semibold">Safe Resolution Rate is never averaged across unlike bots.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{report.personaMetrics.map((persona)=><Metric key={persona.personaCategory} label={persona.personaCategory.replaceAll("_", " ")} value={`${persona.srr}%`} helper={`${persona.safe}/${persona.total} safe resolutions`}/>)}</div>{report.personaMetrics.length?null:<p className="mt-5 text-sm text-[var(--text-muted)]">Persona-level SRR begins with evidence produced after Intelligence Evidence Pipeline v1.0.</p>}</section>
    <section className="overflow-hidden rounded-lg border border-black/7 bg-white shadow-sm"><div className="border-b border-black/6 px-5 py-4"><p className="product-eyebrow">Answer evidence</p><h2 className="mt-1 text-xl font-semibold">Recent governed decisions</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-[#f7f9f8] text-xs text-[var(--text-muted)]"><tr><th className="px-5 py-3">Workspace</th><th className="px-5 py-3">Persona</th><th className="px-5 py-3">Intent</th><th className="px-5 py-3">Disposition</th><th className="px-5 py-3">Retrieval</th><th className="px-5 py-3">Classification</th><th className="px-5 py-3">Reliability</th><th className="px-5 py-3">Versions</th><th className="px-5 py-3">Time</th></tr></thead><tbody className="divide-y divide-black/6">{report.recent.map((item)=><tr key={item.id}><td className="px-5 py-4"><strong>{item.property.name}</strong><small className="block text-[var(--text-muted)]">{item.property.slug}</small></td><td className="px-5 py-4">{item.personaCategory.toLowerCase().replaceAll("_", " ")}</td><td className="px-5 py-4">{item.intent.toLowerCase().replaceAll("_"," ")}</td><td className="px-5 py-4"><span className={`status-pill ${item.safeResolution?"status-success":item.disposition==="ESCALATE"?"status-warning":"status-info"}`}>{item.disposition.toLowerCase()}</span></td><td className="px-5 py-4"><strong className="text-xs">{item.retrievedClaimIds.length} selected · {item.usedClaimIds.length} used</strong><small className="block text-[var(--text-muted)]">{item.nearMissClaimIds.length} near miss</small></td><td className="px-5 py-4">{item.failureClassification.toLowerCase().replaceAll("_", " ")}</td><td className="px-5 py-4"><strong className="text-xs">{item.failureLayer.toLowerCase().replaceAll("_"," ")}</strong><small className="block text-[var(--text-muted)]">{item.escalationTier.replace("TIER_", "T").toLowerCase().replaceAll("_"," ")} · {item.latencyMs}ms · {item.attemptCount} attempt(s)</small></td><td className="px-5 py-4 font-mono text-xs">C{item.constitutionVersion} · B{item.blueprintVersion} · P{item.evidencePipelineVersion}</td><td className="px-5 py-4 text-xs text-[var(--text-muted)]">{item.createdAt.toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</td></tr>)}</tbody></table></div>{report.recent.length?null:<p className="px-5 py-10 text-center text-sm text-[var(--text-muted)]">Evidence collection starts with the next Website Bot answer after deployment.</p>}</section>
  </main>;
}

function Metric({label,value,helper}:{label:string;value:string|number;helper:string}){return <article className="rounded-lg border border-black/7 bg-white p-5 shadow-sm"><p className="product-eyebrow">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-[var(--text-muted)]">{helper}</p></article>}
