import Link from "next/link";
import { formatMoney, getBillingCommandCenter } from "@/lib/billing-super-admin";

export const dynamic = "force-dynamic";
export const revalidate = 0;
const formatDate = (value?: Date | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(value) : "Not scheduled";

export default async function AdminBillingPage() {
  const { customers } = await getBillingCommandCenter();
  const invoices = customers.flatMap((item) => item.organization.invoices.map((invoice) => ({ ...invoice, customer: item.organization.name, organizationId: item.organization.id }))).sort((a,b) => b.createdAt.getTime() - a.createdAt.getTime());
  const active = customers.filter((item) => ["ACTIVE","TRIALING","COMPLIMENTARY"].includes(item.subscription?.status || "")).length;
  const trials = customers.filter((item) => item.subscription?.plan.code === "TRIAL").length;
  const complimentary = customers.filter((item) => item.subscription?.status === "COMPLIMENTARY").length;
  const pastDue = invoices.filter((invoice) => invoice.status === "PAST_DUE" || (invoice.status === "ISSUED" && invoice.dueAt && invoice.dueAt < new Date()));
  const outstanding = invoices.filter((invoice) => !["PAID","VOID"].includes(invoice.status)).reduce((sum,invoice) => sum + invoice.totalPaisa,0);
  const monthlyRecurring = customers.filter((item) => item.subscription?.status === "ACTIVE").reduce((sum,item) => { const plan = item.subscription?.plan; if (!plan) return sum; return sum + (plan.billingInterval === "YEARLY" ? Math.round(plan.amountPaisa / 12) : plan.billingInterval === "QUARTERLY" ? Math.round(plan.amountPaisa / 3) : plan.amountPaisa); },0);

  return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-black/8 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="product-eyebrow">Super Admin · commercial control</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Billing Operations</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#68645c]">Monitor every customer plan, renewal, verified payment, complimentary access and connector charge. This is the operator register—not the customer payment screen.</p></div><Link href="/admin/customers" className="rounded-full bg-[#101010] px-6 py-3 text-sm font-bold text-white">Find a customer</Link></header>
    <nav className="flex gap-2 overflow-x-auto border-b border-black/8 pb-4 text-sm font-bold"><a href="#overview" className="whitespace-nowrap rounded-full bg-[#101010] px-5 py-2.5 text-white">Overview</a><a href="#customers" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Customer billing</a><a href="#payments" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Payments & invoices</a><a href="#addons" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Connectors & add-ons</a></nav>
    <section id="overview" className="grid overflow-hidden border border-white/70 bg-white sm:grid-cols-2 xl:grid-cols-6">{[["Active",active],["Trials",trials],["Complimentary",complimentary],["Past due",pastDue.length],["Outstanding",formatMoney(outstanding)],["Monthly recurring",formatMoney(monthlyRecurring)]].map(([label,value],index) => <div key={label} className={`p-5 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#777168]">{label}</p><strong className={`mt-3 block text-2xl ${label === "Past due" && Number(value) ? "text-[#b53b33]" : ""}`}>{value}</strong></div>)}</section>
    <section id="customers" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Customer billing register" title="Plans, renewal and payment control" /><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-[#f5f2eb] text-[10px] uppercase tracking-[.13em] text-[#68645c]"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Bot</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Payment method</th><th className="px-5 py-4">Renewal / expiry</th><th className="px-5 py-4">Add-ons</th><th className="px-5 py-4">Outstanding</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-black/5">{customers.map(({organization,subscription}) => { const due = organization.invoices.filter((invoice) => !["PAID","VOID"].includes(invoice.status)).reduce((sum,invoice) => sum + invoice.totalPaisa,0); return <tr key={organization.id}><td className="px-5 py-5"><strong>{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.ownerEmail}</small></td><td className="px-5 py-5"><strong>{organization.botProfile?.personaName || organization.botProfile?.category || "Not configured"}</strong></td><td className="px-5 py-5"><strong>{subscription?.plan.name || organization.plan}</strong><small className="mt-1 block text-[#68645c]">{subscription?.status || "NOT SET"}</small></td><td className="px-5 py-5">{subscription?.paymentProvider || "Manual"}</td><td className="px-5 py-5"><strong>{formatDate(subscription?.status === "COMPLIMENTARY" ? subscription.complimentaryEndsAt : subscription?.currentPeriodEnd || subscription?.trialEndsAt)}</strong>{subscription?.status === "COMPLIMENTARY" ? <small className="mt-1 block max-w-44 text-[#68645c]">Complimentary · {subscription.complimentaryReason}</small> : null}</td><td className="px-5 py-5"><strong>{organization.billingAddons.length}</strong><small className="mt-1 block text-[#68645c]">{organization.billingAddons[0]?.name || "None"}</small></td><td className={`px-5 py-5 font-bold ${due ? "text-[#b53b33]" : "text-[#17694f]"}`}>{formatMoney(due)}</td><td className="px-5 py-5"><Link href={`/admin/billing/${organization.id}`} className="inline-flex whitespace-nowrap rounded-full bg-[#101010] px-4 py-2 text-xs font-bold text-white">Open billing record</Link></td></tr>; })}{!customers.length ? <tr><td colSpan={8} className="px-6 py-12 text-center text-[#68645c]">No customers found.</td></tr> : null}</tbody></table></div></section>
    <section id="payments" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Payments & invoices" title="Verified financial record" /><div className="divide-y divide-black/5">{invoices.slice(0,20).map((invoice) => <div key={invoice.id} className="grid gap-3 px-6 py-4 md:grid-cols-[1fr_auto_auto_auto] md:items-center"><span><strong className="block text-sm">{invoice.invoiceNumber} · {invoice.customer}</strong><small className="mt-1 block text-[#68645c]">{formatDate(invoice.createdAt)}{invoice.paymentReference ? ` · Ref ${invoice.paymentReference}` : ""}</small></span><strong>{formatMoney(invoice.totalPaisa)}</strong><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${invoice.status === "PAID" ? "bg-[#eaf7f1] text-[#17694f]" : "bg-[#fff0ee] text-[#a6322a]"}`}>{invoice.status}</span><Link href={`/admin/billing/${invoice.organizationId}`} className="text-xs font-bold text-[#6d5310]">Open →</Link></div>)}{!invoices.length ? <p className="px-6 py-12 text-center text-sm text-[#68645c]">No invoices have been issued.</p> : null}</div></section>
    <section id="addons" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Connectors & add-ons" title="Commercial scope aligned with frontend pricing" /><div className="divide-y divide-black/5">{customers.flatMap((item) => item.organization.billingAddons.map((addon) => ({...addon, customer:item.organization.name, organizationId:item.organization.id}))).map((addon) => <div key={addon.id} className="grid gap-3 px-6 py-4 md:grid-cols-[1fr_auto_auto_auto] md:items-center"><span><strong className="block text-sm">{addon.name} · {addon.customer}</strong><small className="mt-1 block text-[#68645c]">{addon.category.replaceAll("_"," ")} · {addon.provisioningStatus.replaceAll("_"," ")}</small></span><span className="text-xs">Setup <strong>{formatMoney(addon.setupFeePaisa)}</strong></span><span className="text-xs">Recurring <strong>{formatMoney(addon.recurringFeePaisa)}</strong></span><Link href={`/admin/billing/${addon.organizationId}`} className="text-xs font-bold text-[#6d5310]">Manage →</Link></div>)}{!customers.some((item) => item.organization.billingAddons.length) ? <div className="px-6 py-12 text-center"><p className="text-sm text-[#68645c]">No connector charge has been added.</p><p className="mt-2 text-xs text-[#817b72]">Available categories: Google Sheets/Calendar, CRM, E-commerce, PMS/Channel Manager and Custom API.</p></div> : null}</div></section>
    <p className="px-2 text-xs leading-5 text-[#777168]">Full operator evidence remains in Audit Trail. Platform incidents remain in Command Center and Support so Billing stays commercially focused.</p>
  </main>;
}
function Head({eyebrow,title}:{eyebrow:string;title:string}) { return <div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{title}</h2></div>; }
