import Link from "next/link";
import { formatMoney, getBillingCommandCenter, getPlatformAiCostMatrix } from "@/lib/billing-super-admin";
import { getCurrentUser } from "@/lib/auth-server";
import { withTenantDatabaseContext } from "@/lib/security/tenant-database-context";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";
export const revalidate = 0;
const formatDate = (value?: Date | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(value) : "Not scheduled";
const formatPreciseMoney = (paisa: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(paisa / 100);

export default async function AdminBillingPage() {
  const user = await getCurrentUser();
  if (!user || user.role !== "admin") redirect("/login");
  const [{ customers }, platformAi] = await withTenantDatabaseContext({ kind: "platform-admin", actor: `admin-billing:${user.username}` }, () => Promise.all([getBillingCommandCenter(), getPlatformAiCostMatrix()]));
  const invoices = customers.flatMap((item) => item.organization.invoices.map((invoice) => ({ ...invoice, customer: item.organization.name, organizationId: item.organization.id }))).sort((a,b) => b.createdAt.getTime() - a.createdAt.getTime());
  const creditTransactions = customers.flatMap((item) => item.organization.aiCreditTransactions.map((transaction) => ({ ...transaction, customer: item.organization.name, organizationId: item.organization.id }))).sort((a,b) => b.createdAt.getTime() - a.createdAt.getTime());
  const active = customers.filter((item) => ["ACTIVE","TRIALING","COMPLIMENTARY"].includes(item.subscription?.status || "")).length;
  const trials = customers.filter((item) => item.subscription?.plan.code === "TRIAL").length;
  const complimentary = customers.filter((item) => item.subscription?.status === "COMPLIMENTARY").length;
  const pastDue = invoices.filter((invoice) => invoice.status === "PAST_DUE" || (invoice.status === "ISSUED" && invoice.dueAt && invoice.dueAt < new Date()));
  const outstanding = invoices.filter((invoice) => !["PAID","VOID"].includes(invoice.status)).reduce((sum,invoice) => sum + invoice.totalPaisa,0);
  const monthlyRecurring = customers.filter((item) => item.subscription?.status === "ACTIVE").reduce((sum,item) => { const plan = item.subscription?.plan; if (!plan) return sum; return sum + (plan.billingInterval === "YEARLY" ? Math.round(plan.amountPaisa / 12) : plan.billingInterval === "QUARTERLY" ? Math.round(plan.amountPaisa / 3) : plan.amountPaisa); },0);

  return <main className="mx-auto max-w-[1500px] space-y-7 px-4 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-black/8 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="product-eyebrow">Super Admin · commercial control</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Billing Operations</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#68645c]">Monitor every customer plan, renewal, verified payment, complimentary access and AI credit balance. This is the operator register—not the customer payment screen.</p></div><Link href="/admin/customers" className="rounded-full bg-[#101010] px-6 py-3 text-sm font-bold text-white">Find a customer</Link></header>
    <nav className="flex gap-2 overflow-x-auto border-b border-black/8 pb-4 text-sm font-bold"><a href="#overview" className="whitespace-nowrap rounded-full bg-[#101010] px-5 py-2.5 text-white">Overview</a><a href="#platform-cost" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">OpenAI cost</a><a href="#customers" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Customer billing</a><a href="#payments" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Payments & invoices</a><a href="#credits" className="whitespace-nowrap rounded-full border border-black/10 px-5 py-2.5">Credit transactions</a></nav>
    <section id="overview" className="grid overflow-hidden border border-white/70 bg-white sm:grid-cols-2 xl:grid-cols-6">{[["Active",active],["Trials",trials],["Complimentary",complimentary],["Past due",pastDue.length],["Outstanding",formatMoney(outstanding)],["Monthly recurring",formatMoney(monthlyRecurring)]].map(([label,value],index) => <div key={label} className={`p-5 ${index ? "border-t border-black/6 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#777168]">{label}</p><strong className={`mt-3 block text-2xl ${label === "Past due" && Number(value) ? "text-[#b53b33]" : ""}`}>{value}</strong></div>)}</section>
    <PlatformAiCostSection matrix={platformAi} />
    <section id="customers" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Customer billing register" title="Plans, renewal and payment control" /><div className="overflow-x-auto"><table className="w-full min-w-[1300px] text-left text-sm"><thead className="bg-[#f5f2eb] text-[10px] uppercase tracking-[.13em] text-[#68645c]"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Bot</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">AI credits</th><th className="px-5 py-4">Model usage</th><th className="px-5 py-4">Payment method</th><th className="px-5 py-4">Renewal / expiry</th><th className="px-5 py-4">Outstanding</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-black/5">{customers.map(({organization,subscription,aiCredits,modelUsage}) => { const due = organization.invoices.filter((invoice) => !["PAID","VOID"].includes(invoice.status)).reduce((sum,invoice) => sum + invoice.totalPaisa,0); return <tr key={organization.id}><td className="px-5 py-5"><strong>{organization.name}</strong><small className="mt-1 block text-[#68645c]">{organization.ownerEmail}</small></td><td className="px-5 py-5"><strong>{organization.botProfile?.personaName || organization.botProfile?.category || "Not configured"}</strong></td><td className="px-5 py-5"><strong>{subscription?.plan.name || organization.plan}</strong><small className="mt-1 block text-[#68645c]">{subscription?.status || "NOT SET"}</small></td><td className="px-5 py-5"><strong className={aiCredits.remaining ? "text-[#17694f]" : "text-[#b53b33]"}>{aiCredits.remaining.toLocaleString("en-IN")} left</strong><small className="mt-1 block text-[#68645c]">{aiCredits.granted.toLocaleString("en-IN")} added</small></td><td className="px-5 py-5"><strong>{(modelUsage.inputTokens + modelUsage.outputTokens).toLocaleString("en-IN")} tokens</strong><small className="mt-1 block text-[#68645c]">Est. {formatMoney(modelUsage.estimatedCostPaisa)}</small></td><td className="px-5 py-5">{subscription?.paymentProvider || "Manual"}</td><td className="px-5 py-5"><strong>{formatDate(subscription?.status === "COMPLIMENTARY" ? subscription.complimentaryEndsAt : subscription?.currentPeriodEnd || subscription?.trialEndsAt)}</strong>{subscription?.status === "COMPLIMENTARY" ? <small className="mt-1 block max-w-44 text-[#68645c]">Complimentary · {subscription.complimentaryReason}</small> : null}</td><td className={`px-5 py-5 font-bold ${due ? "text-[#b53b33]" : "text-[#17694f]"}`}>{formatMoney(due)}</td><td className="px-5 py-5"><Link href={`/admin/billing/${organization.id}`} className="inline-flex whitespace-nowrap rounded-full bg-[#101010] px-4 py-2 text-xs font-bold text-white">Open billing record</Link></td></tr>; })}{!customers.length ? <tr><td colSpan={9} className="px-6 py-12 text-center text-[#68645c]">No customers found.</td></tr> : null}</tbody></table></div></section>
    <section id="payments" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Payments & invoices" title="Complete verified financial record" /><div className="divide-y divide-black/5">{invoices.map((invoice) => <div key={invoice.id} className="grid gap-3 px-6 py-4 md:grid-cols-[1fr_auto_auto_auto] md:items-center"><span><strong className="block text-sm">{invoice.invoiceNumber} · {invoice.customer}</strong><small className="mt-1 block text-[#68645c]">{formatDate(invoice.createdAt)}{invoice.paymentReference ? ` · Ref ${invoice.paymentReference}` : ""}</small></span><strong>{formatMoney(invoice.totalPaisa)}</strong><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${invoice.status === "PAID" ? "bg-[#eaf7f1] text-[#17694f]" : "bg-[#fff0ee] text-[#a6322a]"}`}>{invoice.status}</span><Link href={`/admin/billing/${invoice.organizationId}`} className="text-xs font-bold text-[#6d5310]">Open →</Link></div>)}{!invoices.length ? <p className="px-6 py-12 text-center text-sm text-[#68645c]">No invoices have been issued.</p> : null}</div></section>
    <section id="credits" className="overflow-hidden border border-white/70 bg-white"><Head eyebrow="Credit transactions" title="Purchases and governed free grants" /><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[#f5f2eb] text-[10px] uppercase tracking-[.13em] text-[#68645c]"><tr><th className="px-5 py-4">Date</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Credits</th><th className="px-5 py-4">Paid</th><th className="px-5 py-4">Reference / reason</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-black/5">{creditTransactions.map((transaction) => <tr key={transaction.id}><td className="px-5 py-4">{formatDate(transaction.createdAt)}</td><td className="px-5 py-4 font-bold">{transaction.customer}</td><td className="px-5 py-4">{transaction.kind === "PURCHASE" ? "Purchased" : "Free grant"}</td><td className="px-5 py-4 font-bold text-[#17694f]">+{transaction.credits.toLocaleString("en-IN")}</td><td className="px-5 py-4">{transaction.amountPaisa ? formatMoney(transaction.amountPaisa) : "₹0"}</td><td className="px-5 py-4"><span className="block">{transaction.paymentReference || transaction.reason || "—"}</span><small className="text-[#68645c]">{transaction.expiresAt ? `Expires ${formatDate(transaction.expiresAt)}` : "No expiry"}</small></td><td className="px-5 py-4"><Link href={`/admin/billing/${transaction.organizationId}`} className="text-xs font-bold text-[#6d5310]">Open →</Link></td></tr>)}{!creditTransactions.length ? <tr><td colSpan={7} className="px-6 py-12 text-center text-[#68645c]">No credit transaction has been recorded.</td></tr> : null}</tbody></table></div></section>
    <p className="px-2 text-xs leading-5 text-[#777168]">Full operator evidence remains in Audit Trail. Platform incidents remain in Command Center and Support so Billing stays commercially focused.</p>
  </main>;
}
function Head({eyebrow,title}:{eyebrow:string;title:string}) { return <div className="border-b border-black/6 px-6 py-5"><p className="product-eyebrow">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{title}</h2></div>; }

function PlatformAiCostSection({ matrix }: { matrix: Awaited<ReturnType<typeof getPlatformAiCostMatrix>> }) {
  const costPerAttempt = matrix.attempts ? Math.round(matrix.estimatedCostPaisa / matrix.attempts) : 0;
  const budgetTone = matrix.budgetState === "OVER" || matrix.budgetState === "AT_RISK" ? "bg-[#fff0ee] text-[#a6322a]" : matrix.budgetState === "WATCH" ? "bg-[#fff6da] text-[#76530b]" : "bg-[#eaf7f1] text-[#17694f]";
  const budgetLabel = matrix.budgetState === "NOT_SET" ? "Budget not configured" : matrix.budgetState === "WITHIN" ? "Within budget" : matrix.budgetState === "WATCH" ? "Watch at 75%" : matrix.budgetState === "AT_RISK" ? "At risk at 90%" : "Budget exceeded";
  return <section id="platform-cost" className="overflow-hidden rounded-[1.4rem] bg-[#101010] text-white shadow-[0_20px_60px_rgba(16,16,16,.14)]">
    <div className="flex flex-col gap-4 border-b border-white/10 px-6 py-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#e1bd4b]">Internal finance · Super Admin only</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">OpenAI Cost &amp; Margin Matrix</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Calendar month to date. This is AiFrogi operating cost—not client billing—and it never charges or pays OpenAI automatically.</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-bold ${budgetTone}`}>{budgetLabel}{matrix.budgetPercent !== null ? ` · ${matrix.budgetPercent}%` : ""}</span></div>
    <div className="grid border-b border-white/10 sm:grid-cols-2 xl:grid-cols-5">{[["OpenAI cost",formatPreciseMoney(matrix.estimatedCostPaisa)],["Model attempts",matrix.attempts.toLocaleString("en-IN")],["Cost / attempt",formatPreciseMoney(costPerAttempt)],["Paid revenue",formatMoney(matrix.paidRevenuePaisa)],["Margin before operations",formatMoney(matrix.grossMarginBeforeOperationsPaisa)]].map(([label,value],index) => <div key={label} className={`p-5 ${index ? "border-t border-white/10 sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-bold uppercase tracking-[.13em] text-white/45">{label}</p><strong className="mt-3 block text-2xl">{value}</strong></div>)}</div>
    <div className="grid gap-3 border-b border-white/10 px-6 py-5 text-sm md:grid-cols-3"><p className="rounded-xl bg-white/5 px-4 py-3 text-white/65"><strong className="block text-xs text-white">Tokens this month</strong>{matrix.inputTokens.toLocaleString("en-IN")} input · {matrix.outputTokens.toLocaleString("en-IN")} output</p><p className="rounded-xl bg-white/5 px-4 py-3 text-white/65"><strong className="block text-xs text-white">Internal budget</strong>{matrix.monthlyBudgetPaisa ? `${formatMoney(matrix.monthlyBudgetPaisa)} monthly cap` : "Configure OPENAI_MONTHLY_BUDGET_PAISE_PER_MONTH"}</p><p className="rounded-xl bg-white/5 px-4 py-3 text-white/65"><strong className="block text-xs text-white">OpenAI billing reminder</strong>{formatDate(matrix.renewalDate)} · manual finance action</p></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/5 text-[10px] uppercase tracking-[.13em] text-white/45"><tr><th className="px-6 py-4">Tenant</th><th className="px-5 py-4">Attempts</th><th className="px-5 py-4">Input tokens</th><th className="px-5 py-4">Output tokens</th><th className="px-5 py-4">OpenAI cost</th></tr></thead><tbody className="divide-y divide-white/10">{matrix.tenants.map((tenant) => <tr key={tenant.organizationId}><td className="px-6 py-4 font-bold">{tenant.name}</td><td className="px-5 py-4">{tenant.attempts.toLocaleString("en-IN")}</td><td className="px-5 py-4">{tenant.inputTokens.toLocaleString("en-IN")}</td><td className="px-5 py-4">{tenant.outputTokens.toLocaleString("en-IN")}</td><td className="px-5 py-4 font-bold">{formatPreciseMoney(tenant.estimatedCostPaisa)}</td></tr>)}{!matrix.tenants.length ? <tr><td colSpan={5} className="px-6 py-10 text-center text-white/50">No tenant usage has been recorded this month.</td></tr> : null}</tbody></table></div>
  </section>;
}
