"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Recommendation = { suggested: boolean; credits: number; reason: string; expiresInDays: number; signal: string };
type Props = { organizationId: string; messageLimit: number; aiReplyLimit: number; messageRatePaisa: number; aiReplyRatePaisa: number; overageApproved: boolean; recommendation: Recommendation };

export function MessagePolicyControl({ organizationId, messageLimit, aiReplyLimit, messageRatePaisa, aiReplyRatePaisa, overageApproved, recommendation }: Props) {
  const router = useRouter();
  const [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [messages, setMessages] = useState(String(messageLimit)), [replies, setReplies] = useState(String(aiReplyLimit));
  const [messageRate, setMessageRate] = useState(String(messageRatePaisa / 100)), [replyRate, setReplyRate] = useState(String(aiReplyRatePaisa / 100)), [approved, setApproved] = useState(overageApproved);
  const [freeCredits, setFreeCredits] = useState(""), [freeReason, setFreeReason] = useState(""), [freeExpiry, setFreeExpiry] = useState("");
  function useSuggestion() { const expiry = new Date(Date.now() + recommendation.expiresInDays * 86400000); setFreeCredits(String(recommendation.credits)); setFreeReason(recommendation.reason); setFreeExpiry(expiry.toISOString().slice(0, 10)); setOpen(true); }
  async function request(body: Record<string, unknown>) { setSaving(true); setError(""); const response = await fetch(`/api/admin/message-matrix/${organizationId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => null); setSaving(false); if (!response.ok) return setError(data?.error || "Could not update credits."); setOpen(false); router.refresh(); }
  return <div>
    {recommendation.suggested ? <button onClick={useSuggestion} className="mb-2 block rounded-full bg-[#fff3c7] px-3 py-2 text-left text-[10px] font-bold text-[#72560c]">Suggested: grant {recommendation.credits} credits</button> : null}
    <button onClick={() => setOpen(!open)} className="rounded-full border border-black/10 px-3 py-2 text-[11px] font-bold">{open ? "Close" : "Set limits / credits"}</button>
    {open ? <div className="mt-3 w-[320px] rounded-2xl border border-black/10 bg-white p-4 shadow-xl"><div className="grid grid-cols-2 gap-2"><label className="text-[10px] font-bold">Message limit<input className="product-input mt-1" inputMode="numeric" value={messages} onChange={e => setMessages(e.target.value)} /></label><label className="text-[10px] font-bold">AI reply limit<input className="product-input mt-1" inputMode="numeric" value={replies} onChange={e => setReplies(e.target.value)} /></label><label className="text-[10px] font-bold">₹ / extra message<input className="product-input mt-1" inputMode="decimal" value={messageRate} onChange={e => setMessageRate(e.target.value)} /></label><label className="text-[10px] font-bold">₹ / extra AI reply<input className="product-input mt-1" inputMode="decimal" value={replyRate} onChange={e => setReplyRate(e.target.value)} /></label></div><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={approved} onChange={e => setApproved(e.target.checked)} />Customer-approved paid overage</label><button disabled={saving} onClick={() => void request({ action: "UPDATE_POLICY", messageLimitOverride: messages, aiReplyLimitOverride: replies, messageOverageRupees: messageRate, aiReplyOverageRupees: replyRate, overageApproved: approved })} className="mt-3 w-full rounded-full bg-[#101010] px-4 py-2 text-xs font-bold text-white">Save policy</button><div className="mt-4 border-t border-black/10 pt-4"><strong className="text-xs">Grant free AI reply credits</strong>{recommendation.suggested ? <p className="mt-1 text-[10px] leading-4 text-[#72560c]">System suggestion: {recommendation.reason} Review before approving.</p> : null}<div className="mt-2 grid grid-cols-2 gap-2"><input className="product-input" inputMode="numeric" placeholder="Credits" value={freeCredits} onChange={e => setFreeCredits(e.target.value)} /><input className="product-input" type="date" aria-label="Optional expiry" value={freeExpiry} onChange={e => setFreeExpiry(e.target.value)} /></div><textarea className="product-input mt-2 min-h-16" placeholder="Required business reason" value={freeReason} onChange={e => setFreeReason(e.target.value)} /><button disabled={saving || !freeCredits || freeReason.trim().length < 5} onClick={() => void request({ action: "GRANT_FREE_CREDITS", credits: freeCredits, reason: freeReason, expiresAt: freeExpiry || null })} className="mt-2 w-full rounded-full bg-[#8a6a16] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Grant free credits</button></div><p className="mt-2 text-[10px] leading-4 text-[#68645c]">Suggestions never grant automatically. Every approved grant is immutable and audited.</p>{error ? <p className="mt-2 text-xs text-[#a6322a]">{error}</p> : null}</div> : null}
  </div>;
}
