"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function MessagePolicyControl({ organizationId, messageLimit, aiReplyLimit, messageRatePaisa, aiReplyRatePaisa, overageApproved }: { organizationId: string; messageLimit: number; aiReplyLimit: number; messageRatePaisa: number; aiReplyRatePaisa: number; overageApproved: boolean }) {
  const router = useRouter(); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const [messages,setMessages]=useState(String(messageLimit)); const [replies,setReplies]=useState(String(aiReplyLimit)); const [messageRate,setMessageRate]=useState(String(messageRatePaisa/100)); const [replyRate,setReplyRate]=useState(String(aiReplyRatePaisa/100)); const [approved,setApproved]=useState(overageApproved);
  async function save(){ setSaving(true);setError(""); const response=await fetch(`/api/admin/message-matrix/${organizationId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"UPDATE_POLICY",messageLimitOverride:messages,aiReplyLimitOverride:replies,messageOverageRupees:messageRate,aiReplyOverageRupees:replyRate,overageApproved:approved})}); const data=await response.json().catch(()=>null);setSaving(false);if(!response.ok)return setError(data?.error||"Could not save policy");setOpen(false);router.refresh(); }
  return <div><button onClick={()=>setOpen(!open)} className="rounded-full border border-black/10 px-3 py-2 text-[11px] font-bold">{open?"Close":"Set limits"}</button>{open?<div className="mt-3 w-[300px] rounded-2xl border border-black/10 bg-white p-4 shadow-xl"><div className="grid grid-cols-2 gap-2"><label className="text-[10px] font-bold">Message limit<input className="product-input mt-1" inputMode="numeric" value={messages} onChange={e=>setMessages(e.target.value)}/></label><label className="text-[10px] font-bold">AI reply limit<input className="product-input mt-1" inputMode="numeric" value={replies} onChange={e=>setReplies(e.target.value)}/></label><label className="text-[10px] font-bold">₹ / extra message<input className="product-input mt-1" inputMode="decimal" value={messageRate} onChange={e=>setMessageRate(e.target.value)}/></label><label className="text-[10px] font-bold">₹ / extra AI reply<input className="product-input mt-1" inputMode="decimal" value={replyRate} onChange={e=>setReplyRate(e.target.value)}/></label></div><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Customer-approved paid overage</label><p className="mt-2 text-[10px] leading-4 text-[#68645c]">Without approval, service stops safely at the limit. Approval must follow the customer’s commercial agreement.</p>{error?<p className="mt-2 text-xs text-[#a6322a]">{error}</p>:null}<button disabled={saving} onClick={save} className="mt-3 w-full rounded-full bg-[#101010] px-4 py-2 text-xs font-bold text-white">{saving?"Saving...":"Save policy"}</button></div>:null}</div>;
}
