"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";

export function SupportTicketActions({ ticketId, initialStatus }: { ticketId: string; initialStatus: string }) {
  const [status, setStatus] = useState(initialStatus === "IN_PROGRESS" ? "INVESTIGATING" : initialStatus === "WAITING_FOR_CUSTOMER" ? "WAITING_FOR_CLIENT" : initialStatus);
  const [message, setMessage] = useState(""), [cause, setCause] = useState(""), [actionTaken, setActionTaken] = useState(""), [verification, setVerification] = useState(""), [prevention, setPrevention] = useState("");
  const [saving, setSaving] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  async function update(body: Record<string, unknown>) {
    setSaving(true); setError(""); setNotice("");
    const response = await fetch("/api/support/tickets", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketId, ...body }) });
    const data = await response.json().catch(() => null); setSaving(false);
    if (!response.ok) { setError(data?.error || "Update failed"); return; }
    setStatus(data.ticket.status); setMessage(""); setNotice("Support request and customer notification updated."); window.location.reload();
  }
  return <section className="rounded-lg border border-black/7 bg-white p-6 shadow-sm"><p className="product-eyebrow">Operator action</p><h2 className="mt-2 text-xl font-semibold">Reply and resolve with evidence</h2><div className="mt-5 grid gap-4"><label><span className="field-label">Reply to customer</span><textarea className="product-input mt-2 min-h-28" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Explain progress or request non-sensitive evidence." /></label><Button disabled={saving || !message.trim()} onClick={() => update({ message })}>Send reply and email</Button><div className="border-t border-black/6 pt-4"><label><span className="field-label">Status</span><select className="product-input mt-2" value={status} onChange={(event) => setStatus(event.target.value)}><option value="OPEN">Open</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="INVESTIGATING">Investigating</option><option value="WAITING_FOR_CLIENT">Waiting for client</option><option value="RESOLVED">Resolved — requires evidence</option><option value="CLOSED">Closed</option></select></label>{status === "RESOLVED" ? <div className="mt-4 grid gap-3"><label><span className="field-label">Root cause</span><textarea className="product-input mt-2 min-h-20" value={cause} onChange={(event) => setCause(event.target.value)} /></label><label><span className="field-label">Action taken</span><textarea className="product-input mt-2 min-h-20" value={actionTaken} onChange={(event) => setActionTaken(event.target.value)} /></label><label><span className="field-label">Verification evidence</span><textarea className="product-input mt-2 min-h-20" value={verification} onChange={(event) => setVerification(event.target.value)} /></label><label><span className="field-label">Prevention / regression control</span><textarea className="product-input mt-2 min-h-20" value={prevention} onChange={(event) => setPrevention(event.target.value)} /></label></div> : null}<Button tone="surface" className="mt-4" disabled={saving} onClick={() => update({ status, cause, actionTaken, verification, prevention })}>Update status</Button></div></div>{notice ? <p className="mt-4 text-sm font-semibold text-[#146b58]">{notice}</p> : null}{error ? <p className="mt-4 text-sm font-semibold text-[#b23a32]">{error}</p> : null}</section>;
}
