import {hospitalityDates} from './hospitality-availability';
export const educationInstitutions={
 school:{name:'Greenfield School — Demo',audience:'Parents & school students',programmes:['Class 1–5','Class 6–8','Class 9–10'],fees:'Fictional tuition: Classes 1–5 ₹36,000/year; Classes 6–8 ₹42,000/year; Classes 9–10 ₹48,000/year. Transport and other charges are not included.',documents:['Birth certificate','Previous school report, where applicable','Parent/guardian identification','Transfer certificate, where applicable'],admissions:'Choose the class and academic year, discuss requirements with admissions, then submit documents through the verified school process. Age and placement eligibility need school review.',info:'Fictional school hours: Monday–Friday, 8:30 AM–3 PM. Library, science lab and sports ground. Transport availability depends on the route; this demo cannot confirm a pickup.',visit:'School tour / parent admission meeting',programLabel:'Which class are you considering?',times:['10:00','11:00'],support:'Attendance, report cards, student fee balances and transport details require a verified parent/guardian or student portal. Public chat cannot retrieve them.'},
 college:{name:'Northbridge College — Demo',audience:'Applicants & college students',programmes:['BSc Computer Science','BCom Commerce','BA English'],fees:'Fictional tuition: BSc Computer Science ₹65,000/year; BCom ₹45,000/year; BA English ₹40,000/year. Hostel and examination charges are excluded.',documents:['Class 12 marksheet','Transfer certificate','Identity document','Programme-specific documents requested by admissions'],admissions:'Choose your degree programme and academic year. Class 12 or an equivalent qualification is a starting requirement; subjects, grades and selection must be checked by the college. No admission or seat is guaranteed.',info:'Fictional admissions desk: Monday–Friday, 9 AM–5 PM. Library, computer labs and campus activities. Hostel allocation, scholarship awards and academic dates need an approved college notice; none is guaranteed here.',visit:'Campus visit / admission counselling',programLabel:'Which degree interests you?',times:['11:00','15:00'],support:'Results, attendance, individual fee balances and student records require verified student-portal access. Public chat cannot retrieve them.'},
 coaching:{name:'Brightpath Coaching — Demo',audience:'Learners & guardians',programmes:['Data Foundations','Digital Marketing','English Communication'],fees:'Fictional course fees: Data Foundations ₹12,000; Digital Marketing ₹9,000; English Communication ₹6,000 per course. No payment is collected here.',documents:['Programme interest','Learning goals','Guardian participation for minors'],admissions:'Select your course and preferred intake. A counsellor checks the appropriate level and batch options. The demo does not enrol students or guarantee batch seats.',info:'Fictional courses: Data Foundations 12 weeks; Digital Marketing 8 weeks; English Communication 6 weeks. Demo counselling is offered on weekdays; teaching timetable requires institute confirmation.',visit:'Course counselling',programLabel:'Which course interests you?',times:['10:00','15:00'],support:'Learner progress, attendance and payment records require verified learner or guardian access. No private records are available in this demo.'}
} as const;
export type EducationKind=keyof typeof educationInstitutions;
export function educationVisitDates(now=new Date()){return hospitalityDates(now).filter(d=>![0,6].includes(new Date(d+'T12:00:00Z').getUTCDay()));}
export function validEducationVisit(kind:EducationKind,programme:string,date:string,time:string,now=new Date()){
 const institute=educationInstitutions[kind];
 return Boolean(institute&&(institute.programmes as readonly string[]).includes(programme)&&educationVisitDates(now).includes(date)&&(institute.times as readonly string[]).includes(time));
}
