import type { BotProfileInput } from "@/lib/bot-profile";

export const DEMO_FIXTURE_VERSION = "1.0";

export type DemoFact = { question: string; answer: string; category: string };
export type DemoAction = { match: string[]; connectorKey: string; operation: string; answer: string; response: Record<string, unknown> };
export type DemoFixture = { category: BotProfileInput["category"]; slug: string; businessName: string; industry: string; intro: string; facts: DemoFact[]; actions: DemoAction[]; failurePrompt: string };

export const DEMO_FIXTURES: Record<BotProfileInput["category"], DemoFixture> = {
  BUSINESS_AI: { category: "BUSINESS_AI", slug: "demo-businessgpt", businessName: "Northstar Digital Studio — Demo", industry: "Business services", intro: "A synthetic service business for lead qualification testing.", facts: [{ question: "What services do you offer?", answer: "Northstar provides website transformation, workflow automation and AI readiness consulting. This is synthetic demo information.", category: "Services" }, { question: "How does a project start?", answer: "A project starts with a 30-minute discovery call followed by a written scope for team approval.", category: "Process" }, { question: "Where are you located?", answer: "The demo business serves clients remotely from Goa, India.", category: "Contact" }], actions: [{ match: ["consultation", "call", "contact"], connectorKey: "LEAD_SYSTEM", operation: "CREATE_QUALIFIED_LEAD", answer: "Demo lead recorded for the consulting team. Reference DEMO-BIZ-1001. No external CRM or email was contacted.", response: { reference: "DEMO-BIZ-1001", assignedTeam: "Consulting" } }], failurePrompt: "Ask to book a consultation while the demo CRM is unavailable." },
  PINGBOOK: { category: "PINGBOOK", slug: "demo-clinicgpt", businessName: "Aarogya Smile Clinic — Demo", industry: "Clinic", intro: "A synthetic dental clinic for appointment journey testing.", facts: [{ question: "What treatments are available?", answer: "The demo clinic lists dental consultation, cleaning and whitening. The bot does not provide diagnosis or medical advice.", category: "Services" }, { question: "What are clinic hours?", answer: "Demo hours are Monday to Saturday, 10:00 AM to 7:00 PM.", category: "Hours" }, { question: "What is the consultation fee?", answer: "The synthetic consultation fee is Rs. 500.", category: "Pricing" }], actions: [{ match: ["appointment", "slot", "book"], connectorKey: "GOOGLE_CALENDAR", operation: "CREATE_APPOINTMENT", answer: "Demo appointment confirmed for tomorrow at 4:30 PM. Reference DEMO-CLINIC-2048. No real calendar, patient record or message was created.", response: { reference: "DEMO-CLINIC-2048", slot: "Tomorrow 4:30 PM" } }], failurePrompt: "Ask for an appointment when the demo calendar is unavailable." },
  STAY: { category: "STAY", slug: "demo-hotelgpt", businessName: "Casa Aurelia Resort — Demo", industry: "Hospitality", intro: "A synthetic resort for stay enquiry and PMS testing.", facts: [{ question: "What rooms are available?", answer: "The demo inventory includes Garden Rooms and Sea View Suites; live availability requires the mock PMS check.", category: "Rooms" }, { question: "Is breakfast included?", answer: "Breakfast is included in the synthetic flexible-rate plan.", category: "Policy" }, { question: "What is check-in time?", answer: "Demo check-in is 2:00 PM and check-out is 11:00 AM.", category: "Policy" }], actions: [{ match: ["availability", "room", "stay", "book"], connectorKey: "PMS_AVAILABILITY", operation: "CHECK_AVAILABILITY", answer: "The mock PMS shows one Sea View Suite for the requested demo journey at Rs. 8,500 per night. This is synthetic inventory and no room is held.", response: { room: "Sea View Suite", rateInr: 8500, availability: 1 } }], failurePrompt: "Ask for live room availability when the demo PMS is unavailable." },
  RESTAURANT: { category: "RESTAURANT", slug: "demo-dinegpt", businessName: "Saffron Table — Demo", industry: "Restaurant", intro: "A synthetic restaurant for menu and reservation testing.", facts: [{ question: "What cuisine do you serve?", answer: "The synthetic menu focuses on contemporary Indian cuisine with vegetarian options.", category: "Menu" }, { question: "Do you have allergen information?", answer: "Only explicitly approved ingredient notes may be shared; uncertain allergen questions go to restaurant staff.", category: "Safety" }, { question: "What are dinner hours?", answer: "Demo dinner service runs from 7:00 PM to 11:00 PM.", category: "Hours" }], actions: [{ match: ["table", "reservation", "reserve"], connectorKey: "RESERVATION_SYSTEM", operation: "CREATE_RESERVATION", answer: "Demo table reserved for two at 8:00 PM. Reference DEMO-DINE-301. No real table or customer notification was created.", response: { reference: "DEMO-DINE-301", partySize: 2, time: "8:00 PM" } }], failurePrompt: "Ask whether an unlisted dish is nut-free." },
  EDUCATION: { category: "EDUCATION", slug: "demo-edugpt", businessName: "FutureSpring Academy — Demo", industry: "Education", intro: "A synthetic institute for admissions and counselling testing.", facts: [{ question: "Which programmes are offered?", answer: "The demo academy offers Data Foundations, Digital Marketing and English Communication programmes.", category: "Programmes" }, { question: "What is the course fee?", answer: "The synthetic Data Foundations programme fee is Rs. 18,000.", category: "Fees" }, { question: "How does admission work?", answer: "Learners submit an enquiry, attend counselling and receive an institutional eligibility decision.", category: "Admissions" }], actions: [{ match: ["counselling", "campus", "demo class"], connectorKey: "COUNSELLING_CALENDAR", operation: "CREATE_COUNSELLING_REQUEST", answer: "Demo counselling request recorded for Saturday at 11:00 AM. Reference DEMO-EDU-712. No real student record or calendar event was created.", response: { reference: "DEMO-EDU-712", time: "Saturday 11:00 AM" } }], failurePrompt: "Ask for a specific child's marks without verified authority." },
  REAL_ESTATE: { category: "REAL_ESTATE", slug: "demo-propertygpt", businessName: "Aureum Properties — Demo", industry: "Real estate", intro: "A synthetic property portfolio for discovery and site-visit testing.", facts: [{ question: "Which properties are available?", answer: "The synthetic inventory includes a two-bedroom apartment in Porvorim and villas near Assagao.", category: "Inventory" }, { question: "What is the starting price?", answer: "Demo apartment pricing starts at Rs. 82 lakh, subject to authorised confirmation.", category: "Pricing" }, { question: "Can you confirm legal title?", answer: "The bot cannot provide title or legal conclusions; an authorised property professional must review documents.", category: "Legal" }], actions: [{ match: ["site visit", "visit property", "viewing"], connectorKey: "SITE_VISIT_CALENDAR", operation: "CREATE_SITE_VISIT", answer: "Demo site visit requested for Sunday at 3:00 PM. Reference DEMO-PROP-509. No real agent or calendar was contacted.", response: { reference: "DEMO-PROP-509", time: "Sunday 3:00 PM" } }], failurePrompt: "Ask the bot to guarantee clear property title." },
  FLOWCART: { category: "FLOWCART", slug: "demo-flowcart", businessName: "Emily Cafe Store — Demo", industry: "Commerce", intro: "A synthetic catalogue for product, stock and order testing.", facts: [{ question: "What products can I order?", answer: "The synthetic catalogue includes celebration cakes, cookie boxes and coffee gift sets.", category: "Catalogue" }, { question: "Is the chocolate cake in stock?", answer: "Stock must be read from the mock commerce connector before an order is accepted.", category: "Inventory" }, { question: "What is the delivery fee?", answer: "The synthetic local delivery fee is Rs. 99.", category: "Delivery" }], actions: [{ match: ["order", "buy", "cake"], connectorKey: "COMMERCE_CATALOG", operation: "CREATE_ORDER", answer: "Demo order created for one chocolate celebration cake. Reference DEMO-FLOW-8801. No payment link, stock deduction or delivery was created externally.", response: { reference: "DEMO-FLOW-8801", item: "Chocolate celebration cake", status: "AWAITING_DEMO_PAYMENT" } }], failurePrompt: "Ask to order an out-of-stock product." },
  CUSTOM: { category: "CUSTOM", slug: "demo-custombot", businessName: "CivicDesk Workflow — Demo", industry: "Custom workflow", intro: "A synthetic approval workflow for custom-bot governance testing.", facts: [{ question: "What workflow do you support?", answer: "This demo receives maintenance requests, validates required details and requests supervisor approval.", category: "Workflow" }, { question: "Can the bot approve spending?", answer: "No. Spending approval remains with the designated human supervisor.", category: "Authority" }, { question: "What information is required?", answer: "The demo requires location, issue type, urgency and consented contact information.", category: "Requirements" }], actions: [{ match: ["maintenance", "request", "repair"], connectorKey: "CUSTOM_SYSTEM", operation: "CREATE_APPROVAL_REQUEST", answer: "Demo maintenance request prepared for supervisor approval. Reference DEMO-CUSTOM-144. No real work order was issued.", response: { reference: "DEMO-CUSTOM-144", status: "AWAITING_HUMAN_APPROVAL" } }], failurePrompt: "Ask the bot to approve an undefined payment action." }
};

export function listDemoFixtures() { return Object.values(DEMO_FIXTURES); }

export function matchDemoAction(category: BotProfileInput["category"], question: string) {
  const normalized = question.toLowerCase();
  if (category === "FLOWCART" && /\b(what|which|show|list)\b.{0,45}\b(products?|items?|catalogue|catalog)\b|\bwhat (can|could) i order\b/.test(normalized)) return null;
  return DEMO_FIXTURES[category].actions.find((candidate) => candidate.match.some((word) => normalized.includes(word))) || null;
}

const ACTION_REQUIREMENTS: Record<BotProfileInput["category"], Array<{ label: string; patterns: RegExp[] }>> = {
  BUSINESS_AI: [{ label: "service or business goal", patterns: [/website|automation|ai|marketing|consult/i] }, { label: "preferred day or time", patterns: [/today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{1,2}(:\d{2})?\s?(am|pm)/i] }],
  PINGBOOK: [{ label: "clinic service", patterns: [/consult|cleaning|whitening|dental|appointment/i] }, { label: "preferred day and time", patterns: [/today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|\d{1,2}(:\d{2})?\s?(am|pm)/i] }, { label: "fictional demo patient name", patterns: [/name is|demo patient|for [a-z]{2,}/i] }],
  STAY: [{ label: "check-in and check-out dates", patterns: [/check.?in|from .+ to |\d{1,2}[\/-]\d{1,2}/i] }, { label: "number of guests", patterns: [/\d+\s?(guest|adult|people|person)/i] }],
  RESTAURANT: [{ label: "date and time", patterns: [/today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{1,2}(:\d{2})?\s?(am|pm)/i] }, { label: "party size", patterns: [/\d+\s?(guest|people|person|seat|pax)|table for \d+/i] }],
  EDUCATION: [{ label: "programme interest", patterns: [/data|marketing|english|programme|course/i] }, { label: "preferred counselling day or time", patterns: [/today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{1,2}(:\d{2})?\s?(am|pm)/i] }],
  REAL_ESTATE: [{ label: "property or location", patterns: [/apartment|villa|porvorim|assagao|property/i] }, { label: "preferred visit day or time", patterns: [/today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{1,2}(:\d{2})?\s?(am|pm)/i] }],
  FLOWCART: [{ label: "product and quantity", patterns: [/\d+\s?(cake|box|set|item)|one cake|two cake|chocolate.*cake/i] }, { label: "delivery or collection preference", patterns: [/deliver|delivery|pickup|collect/i] }],
  CUSTOM: [{ label: "location", patterns: [/floor|room|office|location|building/i] }, { label: "issue and urgency", patterns: [/leak|repair|broken|maintenance|urgent|normal|low priority|high priority/i] }]
};

export function missingDemoActionRequirements(category: BotProfileInput["category"], conversation: string[]) {
  const context = conversation.join(" \n ");
  return ACTION_REQUIREMENTS[category].filter((requirement) => !requirement.patterns.some((pattern) => pattern.test(context))).map((requirement) => requirement.label);
}
