import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/marketing/site-footer";
import { SiteHeader } from "@/components/marketing/site-header";
import { marketingMetadata } from "@/lib/seo";

export const metadata: Metadata = marketingMetadata({
  title: "How to Install an AI Business Bot | AiFrogi",
  description: "Choose an AiFrogi AI Bot, start a 15-day trial, prepare approved intelligence, install one website code and complete controlled Super Admin go-live approval.",
  path: "/install-ai-bot"
});

const journey = [
  ["01", "Choose the AI Bot", "Select BusinessGPT, HotelGPT, ClinicGPT, DineGPT, eduGPT, PropertyGPT, FlowCart or a Custom Business Bot according to the first outcome you want to prove."],
  ["02", "Start the 15-day trial", "Verify the business owner’s email and create a private workspace. Trial controls apply in the backend and automatically pause paid actions after 15 days."],
  ["03", "Build sovereign intelligence", "Approve first-party website pages, documents, structured information, persona, authority, prohibited claims and human escalation rules."],
  ["04", "Copy one installation code", "Use the generated JavaScript for most sites, an iFrame where scripts are restricted, or the same JavaScript in a WordPress Custom HTML block."],
  ["05", "AiFrogi detects the website", "The first valid website load records the installation against the correct tenant. Detection does not automatically expose an unfinished bot to visitors."],
  ["06", "Super Admin makes it live", "AiFrogi checks intelligence, installation, safety and handover readiness. A green Bot Live state enables visitor conversations; Pause or Delete immediately removes live access." ]
];

export default function InstallAiBotPage() {
  return <main className="bg-[#fbfaf7] text-[#101010]"><SiteHeader />
    <section className="relative overflow-hidden bg-[#050505] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(226,198,109,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(226,198,109,.08)_1px,transparent_1px)] [background-size:76px_76px]" /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div><p className="product-eyebrow text-[#e2c66d]">Self-service activation</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-7xl">Install your AI Bot. Keep go-live controlled.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/62">AiFrogi turns a selected business outcome into approved intelligence, installation code and a traceable live bot—without asking customers to surrender their business knowledge or credentials.</p><Link href="https://app.aifrogi.com/register?source=install-ai-bot" className="mt-8 inline-flex min-h-12 items-center rounded-md bg-[#8a6a16] px-6 text-sm font-bold text-white">Start 15-day trial</Link></div><div className="rounded-2xl border border-[#8a6a16]/45 bg-white/5 p-6 backdrop-blur"><p className="text-xs uppercase tracking-[.18em] text-[#e2c66d]">Controlled state model</p><div className="mt-5 space-y-3">{["Code ready", "Installation detected", "Awaiting Super Admin", "Bot Live", "Paused or deleted safely"].map((state, index) => <div key={state} className="flex items-center gap-4 border-b border-white/10 pb-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${index === 3 ? "bg-[#16794a] text-white" : "bg-[#8a6a16] text-white"}`}>{index === 3 ? "✓" : index + 1}</span><span className="font-medium">{state}</span></div>)}</div></div></div></section>
    <section className="border-b border-black/10 bg-white px-5 py-8 sm:px-8"><div className="mx-auto max-w-7xl"><a href="/downloads/AiFrogi-Client-Onboarding-Prerequisites.pdf" download className="group grid gap-5 rounded-2xl border border-[#8a6a16]/35 bg-[#f7f4ed] p-5 transition hover:border-[#8a6a16] hover:bg-[#f3e5b5]/45 sm:grid-cols-[64px_1fr_auto] sm:items-center sm:p-7"><span className="grid h-16 w-16 place-items-center rounded-xl bg-[#101010] text-[#e2c66d]" aria-hidden="true"><svg viewBox="0 0 24 24" className="h-8 w-8 fill-none stroke-current" strokeWidth="1.7"><path d="M7 2.75h7l4 4V21.25H7z"/><path d="M14 2.75v4h4M9.5 12.25h5M9.5 15.5h5M9.5 18.75h3.25"/></svg></span><span><span className="product-eyebrow text-[#8a6a16]">Client preparation PDF</span><strong className="mt-1 block text-xl font-semibold tracking-[-.02em] sm:text-2xl">Download AI Bot onboarding instructions</strong><span className="mt-2 block max-w-3xl text-sm leading-6 text-[#68645c]">Prepare business details, approved knowledge, photos, Google location, connector ownership, website access, security boundaries and preview sign-off before completing onboarding.</span></span><span className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-[#8a6a16] px-5 text-sm font-bold text-white">Download PDF <span aria-hidden="true">↓</span></span></a></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><p className="product-eyebrow">How the system works</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">From product selection to verified live conversations.</h2><div className="mt-12 border-t border-black/12">{journey.map(([number, title, copy]) => <article key={number} className="grid gap-4 border-b border-black/12 py-7 md:grid-cols-[90px_280px_1fr]"><span className="font-mono text-sm text-[#8a6a16]">{number}</span><h3 className="text-xl font-semibold">{title}</h3><p className="max-w-3xl leading-7 text-[#68645c]">{copy}</p></article>)}</div></div></section>
    <section className="bg-[#101010] px-5 py-16 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-3">{[["JavaScript", "Recommended", "One asynchronous script detects installation and loads the tenant-bound bot only after approval."], ["iFrame", "Restricted platforms", "A contained embed is available where custom JavaScript cannot be used."], ["WordPress", "No plugin required", "Paste the generated script into a Custom HTML block or approved footer-code area."]].map(([title, label, copy]) => <div key={title} className="border-t border-[#8a6a16] pt-5"><p className="text-xs uppercase tracking-[.16em] text-[#e2c66d]">{label}</p><h3 className="mt-3 text-2xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-white/58">{copy}</p></div>)}</div></section>
    <section className="px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="product-eyebrow">Operational control</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Live is an explicit decision.</h2></div><div className="space-y-5 text-base leading-8 text-[#68645c]"><p><strong className="text-[#101010]">Client Admin</strong> maintains approved business information, persona and day-to-day conversations.</p><p><strong className="text-[#101010]">AiFrogi Super Admin</strong> sees installation detection, confirms readiness, makes the bot live and can pause, soft-delete or restore it with an activity trail.</p><p><strong className="text-[#101010]">Visitors</strong> can reach the bot only while its tenant and Website channel are live. Paused and deleted bots stop serving conversations without erasing sovereign business data.</p></div></div></section>
    <SiteFooter /></main>;
}
